### ISSUE TITLE
1-02: new units; Deadline 17.5.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#105]
OSCAR/Requirements indicates that these units are used to express the result of the measurements of certain variables:
- **[Rad/s]** for 8,\Earth\Earth Rotation in table 1-01-02
- **[ mGal ]** where : 1 Gal = 0.01 m s-2. for 11,\Earth\Gravity field
- **[ E ]** , Eötvös (1 E = 1 mGal / 10 km) for 12,\Earth\Gravity gradients
- **[ psu ]**, Practical Salinity Unit, close to 1, determined by CTD for 91,\Ocean\Basic Physical Properties\Ocean salinity
-  **[ t/ha (tons/hectare) ]** for 423,\Terrestrial\Land surface\Vegetation\Biomass,Biomass

These units are still missing in the table 1-02 "units". Should they be added?

**Comment by LuisaIckes** [comment]
Was this discussed in the last teleconference/is there already an opinion of these units should be added or not?

**Comment by nuneslf** [comment]
This brings me back to the issue of WMDS using code table C-6 (from the WMO Codes Registry at  http://codes.wmo.int/common/_unit);
I believe that TT-WMD has adopted that table C-6 for the units, but I see 160 entries in our table, while C-6 has only 158;
@LuisaIckes, Could I ask you to do a mapping of both tables including the "additional units" above mentioned in this issue #105, please?

**Comment by joergklausen** [comment]
TT-WMD has indeed adopted this table from C-6 in an attempt to re-use what already exists. However, if we need these extensions, then we must include them in our code table. The TT-CM should be informed about these additions and should extend C-6 accordingly. If they do not agree to this or do not offer an acceptable alternative, then we have no other choice but to decouple our code table from C-6. Can the Secretariat please submit these amendments to TT-CM on behalf of TT-WMD?

**Comment by nuneslf** [comment]
I believe @joergklausen wanted to say IPET-CM, a team that is under Enrico's responsibility.
@efucile can you comment on this please?

**Comment by LuisaIckes** [comment]
Sure, the mapping looks the following:

Entries the unit table C-6 from the code registry has, which we do not have in our table:
- all the unit prefixes (standalone without a unit): yotta, zetta, yocto, zepto, exa, giga, mega, peta, tera, atto, centi, deci, deca, femto, hecto, kilo, milli, nano, pico, micro [total of 20 table entries] -> this makes sense for us not to have since that are not really units
- '1' dimensionless [1 table entry]

Entries that we have but are missing in the unit table C-6 from the code registry:
- inch
- kHz	kilohertz
- MHz      megahertz
- GHz	Gigahertz
- THz	tetrahertz

+ the entries added in the last release:
- unknown
- μmol_mol-1	micromoles per mole	
- nmol_mol-1	nanomoles per mole	
- pmol_mol-1	picomoles per mole	
- mmol_mol-1	millimoles per mole	
- mBq_m-3	millibecquerels per cubic metre	
- μmol_kg-1	micromoles per kilogram	
- μmol_l-1	micromoles per litre	
- μg_m-3_20C	micrograms per cubic metre at 20 degrees	
- μg-m-3_25C	micrograms per cubic metre at 25 degrees	
- mg_m-3_25C	milligrams per cubic metre at 25 degrees	
- ng_m-3	nanograms per cubic metre	
- μg_N_m-3	microgram N per cubic metre	
- μg_C_m-3	microgram C per cubic metre	
- μg_S_m-3	microgram S per cubic metre	
- μg_Cl_m-3	microgram CI per cubic metre	
- mg_N_l-1	milligram N per litre	
- mg_S_l-1	milligram S per litre

+ the entries from this issue:
- [Rad/s] for 8,\Earth\Earth Rotation in table 1-01-02
- [ mGal ] where : 1 Gal = 0.01 m s-2. for 11,\Earth\Gravity field
- [ E ] , Eötvös (1 E = 1 mGal / 10 km) for 12,\Earth\Gravity gradients
- [ psu ], Practical Salinity Unit, close to 1, determined by CTD for 91,\Ocean\Basic PhysicalProperties\Ocean salinity
- [ t/ha (tons/hectare) ] for 423,\Terrestrial\Land surface\Vegetation\Biomass,Biomass

So we have additional 23 table entries (if I did not misscount).

**Comment by joergklausen** [comment]
@LuisaIckes Thanks for pulling this together. 
Going through the current table 1-02, I note
Line 55: C_-1 should have another notation, maybe C_(100_m)-1
Line 109: m2_-1 should have another notation, maybe m2/3_s-1

Regarding the entries from this issue, the following changes for consistency:
rad_s-1, radian per second
mGal, milligal (where 1 Gal = 0.01 m_s-2
E, Eötvös (where 1 E = 1 mGal / 10 km)
t_ha, (metric) ton per hectare

Further, we need the following additional entries
ppmv, parts per million by volume dry air
ppbv, parts per billion by volume dry air
pptv, parts per trillion by volume dry air

**Comment by efucile** [comment]
I just want to remind you that this table is maintained by IPET-CM. We need to make a list of the additional entries compared to the official version of the table and submit a request to IPET-CM for approval. We don't have freedom of entering new items in the table. We need first to request IPET-CM to approve the entries and then we can add the entries to the table. We need to involve @ashimazaki who is working on the next fast track.
This is very urgent and it is probably worth to open an issue for it.

**Comment by nuneslf** [comment]
@efucile We have agreed to treat the code table for units as ours (TT-WMD) because we need some more variables (and actually, we added already new variables in the last releases); Ideally, in the future we would share several code tables with IPET-CM, but for the moment I'm afraid it would take too long to discuss and have agreement between the two teams on one single table - we could aim to do that for the next round of approval and move ahead now with this one? Thanks

**Comment by LuisaIckes** [comment]
Line 55: C_-1 should have another notation, maybe C_(100_m)-1 
-> I would suggest C_100m-1. That would be most consistent as it seams to me when browsing through the table (e.g. knots per 1000 metres is kt_km-1). There are never (see other comment below) brackets used and _ is always "per", so in case we leave the brackets it would better be C_(100m)-1.

Line 109: m2_-1 should have another notation, maybe m2/3_s-1
-> I agree!

When browsing through the table I found two more inconsistencies:
line 110: log_(m-1)	logarithm per metre	
line 111: log_(m-2)	logarithm per square metre
Both do not need the brackets and it would be more consistent to remove them.

**Comment by nuneslf** [comment]
I'm supportive of Jörg's proposals and Luisa's changes.
Additionally, looking at '1' dimensionless, I think that we should also have it in codetable 1-02, taking into account the variables that are not measured, rather classified, e.g. "present weather"

**Comment by LuisaIckes** [comment]
@nuneslf : Ok, I will add 1 dimensionless as well!
@joergklausen : are you also happy with the changes I suggested? Then I would go ahead and implement all the changes in the unittable.

**Comment by joergklausen** [comment]
@nuneslf I am okay with adding unit '1' for dimensionless, but I do not agree with Luis' reasoning: For classifications, the unit value to chose is 'inapplicable'.
@LuisaIckes The underscore '_' in fact denotes a multiplication, not a division ('per'). Number following a symbol indicate an exponent, and the division is implied by using the hyphen '-' in front of the exponent. Parentheses help to group what needs to be together
- line 110: should really be log(m-1) because there is no multiplication involved
- line 111: should really be log(m-2) ibid
- Line 55: should be C_(100m)-1 to be consistent with the rules above
If you all agree, then please close and proceed.

**Comment by LuisaIckes** [comment]
@joergklausen : Ok!

**Comment by LuisaIckes** [comment]
@joergklausen : And a comment to your comment to Luis: we do not have inapplicable in the unit table (that was decided at a different point), so dimensionless is indeed important.

**Comment by LuisaIckes** [comment]
New summary of difference between our unit table and the unit table C-6 from the code registry:

Entries, which we do not have in our table:
- all the unit prefixes (standalone without a unit): yotta, zetta, yocto, zepto, exa, giga, mega, peta, tera, atto, centi, deci, deca, femto, hecto, kilo, milli, nano, pico, micro [total of 20 table entries] -> this makes sense for us not to have since that are not really units

Entries that we have but are missing in the unit table C-6 from the code registry:
- inch
- kHz	kilohertz
- MHz      megahertz
- GHz	gigahertz
- THz	terahertz

+ the entries added in the last release:
- unknown
- μmol_mol-1	micromoles per mole	
- nmol_mol-1	nanomoles per mole	
- pmol_mol-1	picomoles per mole	
- mmol_mol-1	millimoles per mole	
- mBq_m-3	millibecquerels per cubic metre	
- μmol_kg-1	micromoles per kilogram	
- μmol_l-1	micromoles per litre	
- μg_m-3_20C	micrograms per cubic metre at 20 degrees	
- μg-m-3_25C	micrograms per cubic metre at 25 degrees	
- mg_m-3_25C	milligrams per cubic metre at 25 degrees	
- ng_m-3	nanograms per cubic metre	
- μg_N_m-3	microgram N per cubic metre	
- μg_C_m-3	microgram C per cubic metre	
- μg_S_m-3	microgram S per cubic metre	
- μg_Cl_m-3	microgram CI per cubic metre	
- mg_N_l-1	milligram N per litre	
- mg_S_l-1	milligram S per litre

+ the entries from this issue:
- rad_s-1          radian per second
- mGal             milligal	
- E	                Eötvös	
- t_ha-1	        (metric) ton per hectare	
- psu	        practical salinity unit	
- ppmv            parts per million by volume dry air
- ppbv             parts per billion by volume dry air
- pptv              parts per trillion by volume dry air

So we have additional 31 table entries (missing 20 - prefixes, see above).

**Comment by LuisaIckes** [comment]
Changes can be found in branch [issue105](https://github.com/wmo-im/wmds/tree/105).
