### ISSUE TITLE
New networks to code list 2-02; Deadline: 31.12.2019

### ISSUE THREAD

**Issue by richard-olav** [wmo-im/wmds#126]
Need to add ACTRIS, GAW-WDCA and GAW-WDCRG as a valid programAffiliation in the Program Affiliation code table.

**Comment by LuisaIckes** [comment]
Please also provide name and definition here.

**Comment by richard-olav** [comment]
The name can be the same as above (ACTRIS, GAW-WDCA and GAW-WDCRG). The description could be:

ACTRIS: European Research Infrastructure for the observation of Aerosol, Clouds and Trace Gases
GAW-WDCA: GAW World Data Centre for Aerosols
GAW-WDCRGG: GAW World Data Centre for Reactive Gases

**Comment by LuisaIckes** [comment]
Thanks!

**Comment by joergklausen** [comment]
GAW-WDCA and GAW-WDCRG are not programs/networks in the understanding of this code list. ACTRIS may be included either as GAW Contributing or GAW Other, depending on the existence of an LoA with WMO.

Sent from my iPhone

On 30 Sep 2019, at 03:17, richard-olav <notifications@github.com> wrote:

﻿

The name can be the same as above (ACTRIS, GAW-WDCA and GAW-WDCRG). The description could be:

ACTRIS: European Research Infrastructure for the observation of Aerosol, Clouds and Trace Gases
GAW-WDCA: GAW World Data Centre for Aerosols
GAW-WDCRGG: GAW World Data Centre for Reactive Gases

**Comment by joergklausen** [comment]
@LuisaIckes : WDCA and WDCRG are GAW World Data Centers, not program affiliations, and they will not be included in table 2-02. GALION and GAW-PFR are in this code table because they are genuine programs/networks. WDCRGG is a typo. The status of ACTRIS in GAW needs to be verified.

**Comment by LuisaIckes** [comment]
@richard-olav : 
I would say there is no need to add/change anything in terms of GAW-WDCA and GAW-WDCRGG because WDCA and WDCRGG exist in the list of data centres. However, if the name should be changed and GAW needs to be included that would be a change we could do.

@richard-olav @joergklausen : What is the status of ACTRIS? Should this be added to the network list or is this suggestion rejected?

**Comment by joergklausen** [comment]
The WDCs are known w/o the prefix GAW, and they have this status within WMO irrespective of this particular program. So, in my view, no change is needed.
Regarding the status and position of ACTRIS in the program/network hierarchy, the plan is to discuss this during the SSC OPAG EPAC Meeting 11-14 Nov.

Sent from my iPhone

On 5 Nov 2019, at 12:32, LuisaIckes <notifications@github.com> wrote:

﻿

@richard-olav<https://github.com/richard-olav> :
I would say there is no need to add/change anything in terms of GAW-WDCA and GAW-WDCRGG because WDCA and WDCRGG exist in the list of data centres. However, if the name should be changed and GAW needs to be included that would be a change we could do.

@richard-olav<https://github.com/richard-olav> @joergklausen<https://github.com/joergklausen> : What is the status of ACTRIS? Should this be added to the network list or is this suggestion rejected?

**Comment by LuisaIckes** [comment]
Good!

**Comment by joergklausen** [comment]
[WMDS_Validation_Report_126_Code_Table_2-02_v0.0.docx](https://github.com/wmo-im/wmds/files/4629655/WMDS_Validation_Report_126_Code_Table_2-02_v0.0.docx)

**Comment by atverm** [comment]
I agree that ICOS RI (Integrated Carbon Observation System Research Infrastructure should be added as contributing network. We recently started discussions with Drasko Vasiljevic on how to initiate the automated metadata exchange on station metadata, as some station metadata is completely outdated.

**Comment by efucile** [comment]
Agreed change to be implemented.

It is recommended to add 2 new entries to the codelist 2-02  (http://codes.wmo.int/wmdr/ProgramAffiliation) and to include these in OSCAR/Surface with the paths given below:

Notation | Name | Path in OSCAR/Surface | Definition
-- | -- | -- | --
ACTRIS | ACTRIS | WIGOS > GAW > GAW   Other elements > ACTRIS | Aerosol, Clouds and Trace Gases Research   Infrastructure, www.actris.eu
ICOS | ICOS | WIGOS > GAW > GAW   Contributing networks > ICOS | Integrated Carbon Observation System, www.icos-cp.eu

If/when the status of ACTRIS with respect to GAW changes, the OSCAR/Surface path can be updated easily without affecting the code table.
There are 2 more complementary issues that propose additions to this code table: https://github.com/wmo-im/wmds/issues/161 https://github.com/wmo-im/wmds/issues/157. These are not in conflict.

**Comment by efucile** [comment]
requested change implemented in https://github.com/wmo-im/wmds/tree/issue-126

**Comment by efucile** [comment]
@joergklausen we implemented the change in this brach https://github.com/wmo-im/wmds/tree/issue-126 Can you check that it is correct?

**Comment by IgorZahumensky** [comment]
Karl, PLEASE wait with changes

**Comment by joergklausen** [comment]
I confirm new entries on row 3 and 217 are correct.

**Comment by amilan17** [comment]
Approved by FT 2020-2
