### ISSUE TITLE
merge tables 8-03-x into 8-04

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#141]
During the TT-WMD teleconference  it was discussed to merge 8-03-x under 8-04
Reviewing the action I am not sure that this has to be done now and I think that requires more examination.
I am not sure how we want to implement this and it is better to delay it to a new version.

**Comment by LuisaIckes** [comment]
Same as [here](https://github.com/wmo-im/wmds/issues/140):
The problem is how to actually represent a "hierarchy" in our "flat" list of tables etc.. 
I agree with Enrico to delay this for the next release.

**Comment by nuneslf** [comment]
Same as [here](https://github.com/wmo-im/wmds/issues/140):
8-03 and 8-04 are different elements in the WMDS (WMO-No.1192), so we need to avoid inconsistency;
[Quality flag (8-03) and Quality flagging system (8-04)]

**Comment by efucile** [comment]
@joergklausen 
mapping of WIGOS standard ID to codelist
8-04  http://codes.wmo.int/wmdr/QualityFlagSystem
8-03-01  http://codes.wmo.int/bufr4/codeflag/0-33-020
8-03-02 http://codes.wmo.int/wmdr/QualityFlagOGC

I don't think that any change is required in this case. It is only the mapping of the WMDS to the codelist that counts and the codelist can belong to a different domain.

**Comment by efucile** [comment]
The only action is to delete 8-03-01.csv from this repository because it belongs to BUFR

**Comment by efucile** [comment]
branch implementing this change https://github.com/wmo-im/wmds/tree/issue140

**Comment by joergklausen** [comment]
> @joergklausen
> mapping of WIGOS standard ID to codelist
> 8-04  http://codes.wmo.int/wmdr/QualityFlagSystem
> 8-03-01  http://codes.wmo.int/bufr4/codeflag/0-33-020
> 8-03-02 http://codes.wmo.int/wmdr/QualityFlagOGC
> I don't think that any change is required in this case. It is only the mapping of the WMDS to the codelist that counts and the codelist can belong to a different domain.

I don't have a problem with removing 8-03-01 and strictly refer to the corresponding BUFR codelist. However, I still believe we must treat this suite of tables exactly the same way as the 4-03/4-04 case, for one because we don't have a way of specifying and using a URL that points to codes.wmo.int/bufr/…: 8-04 http://codes.wmo.int/wmdr/QualityFlagSystem as the parent table has elements that refer to daughter tables (currently only 2, but more are expected to come), and we need a consistent approach of specifying the elements from these tables, particularly in the exports from OSCAR/Surface. 
 
My proposal specifically:
8-04 http://codes.wmo.int/wmdr/QualityFlagSystem: leave untouched, with the 2 relevant entries
- http://codes.wmo.int/wmdr/QualityFlagSystem/waterML2.0
- http://codes.wmo.int/wmdr/QualityFlagSystem/bufr033020

Elements in these tables will be referenced after a slash (/) like for the 4-03/4-04 table case. The challenge is that a link like 
http://codes.wmo.int/wmdr/QualityFlagSystem/bufr033020/<entry from table> needs to resolve, so the question is how these entries can be re-directed to the codes.wmo.int/bufr/… URL.

The following links need to be updated:
- http://codes.wmo.int/wmdr/QualityFlagCIMO --> ../bufr033020 (with a redirect to codes.wmo.int/bufr/…
- http://codes.wmo.int/wmdr/QualityFlagOGC --> ../waterML2.0

**Comment by efucile** [comment]
@joergklausen here we have two options 
1. To clone the BUFR table in the wmdr space. In this case the new table was copied at a given time from the BUFR and is now a new entity that doesn't need to be linked to the BUFR original table.
http://codes.wmo.int/wmdr/QualityFlagSystem/BUFR would be my suggestion in this case. This is consistent with WaterML2
2. To refer to the BUFR table. In this case, we are forced to use the URI of the table and we don't have any redirect option. 

I am also proposing to replace waterML2.0 with waterML2   (better to avoid the unnecessary dot)

**Comment by joergklausen** [comment]
@efucile: I understand that redirect is not possible. In principle, I prefer your option 2, but to do that, we need to include the URL to the specific table hosted outside /wmdr in the 8-04 http://codes.wmo.int/wmdr/QualityFlagSystem, i.e. a separate column 'URL'. We need this for reference (and for the XML engine), because obviously, the actual tables can be hosted anywhere in principle. 

I did not use .../BUFR because we may also want to recommend other BUFR tables in the future. So I think we should stick with something specific, e.g. bufr033020. 

I prefer 'waterML20' to be able to include future minor versions of waterML2. 

So, 
- 8-04 http://codes.wmo.int/wmdr/QualityFlagSystem with an additional column URL
Table 8-04 would then have an entry
- notation: bufr033020, and URL: http://codes.wmo.int/bufr4/codeflag/0-33-020
Table 8-03-01 can be dropped.
Also, is there a direct URL pointing to the waterML20 table, or is this one we should clone and maintain separately under ../wmdr ? If we can refer to a table hosted elsewhere, we can also drop 8-03-02.

**Comment by efucile** [comment]
@joergklausen ok. 
I am going to keep waterML2.0 I think it's clearer than waterML20.

**Comment by efucile** [comment]
@joergklausen the situation is the same for waterML2.0. The codelist is maintained at an external URL URL: http://www.opengis.net/def/waterml/2.0/quality we should not copy the table and delete also 8-03-02
