### ISSUE TITLE
Review changes discussed in TT-WMD-7

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#15]

**Comment by HoratN** [comment]
table 4-03-01: Should slope be in degrees or in % ?

**Comment by HoratN** [comment]
table 4-04: How is 'Equipment maintenance' different from 'preventive maintenance'?

**Comment by KarlBureau** [comment]
Slope can be reported in degrees or percent rise. I see the explanation is written in percent so I suggest we stay with that. Slope in degrees will be 0 to 90°, or 0 to infinity for percent.

Equipment maintenance is focused on the equipment, while preventative maintenance may be more general, such as cleaning the instrument shelter, painting, etc.

**Comment by HoratN** [comment]
The reason why I am asking whether to keep percent or degrees is that OSCAR is currently using degrees. Thus the data is so far submitted in degrees. Do we nevertheless stick to percent?

**Comment by HoratN** [comment]
**table 4-07: unknown and inapplicable:** the name column is restricted to 3 bytes in OSCAR. What do you think about taking 'Unk' and 'Ina' for the Name_e entry and _"(Inapplicable - The value is not applicable.)"_ and _"(Unknown - The value is unknown or missing.)"_ for the Definition_e entries?
Go to https://github.com/wmo-im/wmds/compare/review_TT-WMD-7 and scroll down to see the changes.

**Comment by KarlBureau** [comment]
> The reason why I am asking whether to keep percent or degrees is that OSCAR is currently using degrees. Thus the data is so far submitted in degrees. Do we nevertheless stick to percent?

Personally I would prefer to use degrees, and if that is the convention in OSCAR/Surface, it would be worthwhile to make the change.

**Comment by KarlBureau** [comment]
> **table 4-07: unknown and inapplicable:** the name column is restricted to 3 bytes in OSCAR. What do you think about taking 'Unk' and 'Ina' for the Name_e entry and _"(Inapplicable - The value is not applicable.)"_ and _"(Unknown - The value is unknown or missing.)"_ for the Definition_e entries?
Ukn for Unknown, Yes
Ina for Inapplicable, No. I would prefer NA as it is used a lot in the English speaking world for "Not applicable".

**Comment by efucile** [comment]
Just a general comment of methodology. We should not have one issue for a number of items to be discussed. We should have one issue per item. It doesn't cost anything to open one issue per item to review. Moreover the name of the issue should clarify what is discussed. If we need to group issues there are several ways to do that. One is to create labels to be assigned.
For example all the items of discussion coming out from TT-WMD-7 could have one issue each where the discussion will take place and they can all be labelled TT-WMD-7 to group all of them under a topic.
This would facilitate meeting and teleconferences because they will have a review of the open issues in the agenda.
