### ISSUE TITLE
2-02 Programs/networks: new additions to GOOS/Argo

### ISSUE THREAD

**Issue by anthoninlize** [wmo-im/wmds#157]
Hello all,

A few additions to this code list:

* \Co-sponsored\GOOS\Argo\AtlantOS_H2020

* \Co-sponsored\GOOS\Argo\Argo PERU

* \Co-sponsored\GOOS\Argo\Argo UW-SOCCOM
The Southern Ocean Carbon and Climate Observations and Modeling project (SOCCOM) is an NSF-sponsored program focused on unlocking the mysteries of the Southern Ocean and determining its influence on climate.
Housed at Princeton University and administered by the Princeton Environmental Institute, SOCCOM draws on the strengths of teams of investigators across the U.S. as well as participating in international observational and simulation efforts.
SOCCOM is supported by the National Science Foundation under NSF Award PLR-1425989.

* \Co-sponsored\GOOS\Argo\MOCCA-EU

* \Co-sponsored\GOOS\Argo\MOCCA-GER

* \Co-sponsored\GOOS\Argo\MOCCA-IT

* \Co-sponsored\GOOS\Argo\MOCCA-NETH

* \Co-sponsored\GOOS\Argo\MOCCA-POL

* \Co-sponsored\GOOS\Argo\Argo NIMS/KMA
The primary practical goal of METRI/ARGO is to provide an enhanced real-time capability for measurement of temperature and salinity through the upper 2000 m of the ocean, to contribute to a global description of the seasonal cycle and inter-annual variability of the upper ocean thermohaline circulation, to contribute to short-term ocean forecasting, to provide boundary conditions for forecasting, and to contribute to seasonal in inter-annual atmospheric forecasts.

* \Co-sponsored\GOOS\Argo\Argo UW-MBARI
Why measure nitrate? 
Nitrate is a key phytoplankton nutrient. The concentration of nitrate regulates phytoplankton growth in much of the ocean. In a warming climate, the transport of nitrate from deep water may diminish and reduce primary production in the ocean. 

* \Co-sponsored\GOOS\Argo\Argo UW-TPOS eq.

* \Co-sponsored\GOOS\Argo\Argo WHOI-SODA eq.

* \Co-sponsored\GOOS\Argo\Argo Morocco

* \Co-sponsored\GOOS\Argo\Argo WHOI-Loop Current eq.

* \Co-sponsored\GOOS\Argo\Euro-Argo RISE

* \Co-sponsored\GOOS\Argo\Argo FPAII-GMMC

thanks!

**Comment by joergklausen** [comment]
This is an extension of the list of ARGO programs, submitted by the designated expert, thus non-controversial.
@anthoninlize Please update Table 2-02.csv, creating Notation and Name and commit.

**Comment by anthoninlize** [comment]
@joergklausen I need details on how to update this CSV, i.e. :
- you don't need the path ? To identify it's Argo programs
- do I need to insert them following alphabetical order?
- is it under the folder 'tables' or 'tables_en'?
- do I have rights to push it direclty or do I need to go through a pull request?

Considering all of these, I'm starting to wonder if this action was really adressed to me actually.

**Comment by joergklausen** [comment]
Please add a short explanation of what these acronyms mean.

**Comment by anthoninlize** [comment]
Here's the validation report for these new entries as well as the ones from https://github.com/wmo-im/wmds/issues/161

[2020-05-argo_dbcp_programmes.docx](https://github.com/wmo-im/wmds/files/4649241/2020-05-argo_dbcp_programmes.docx)

**Comment by joergklausen** [comment]
Uploaded on behalf of @anthoninlize 
[2020-05-argo_dbcp_programmes.docx](https://github.com/wmo-im/wmds/files/4716689/2020-05-argo_dbcp_programmes.docx)

**Comment by joergklausen** [comment]
v0.2 after editorial review
[2020-05-argo_dbcp_programmes.docx](https://github.com/wmo-im/wmds/files/4716799/2020-05-argo_dbcp_programmes.docx)

**Comment by amilan17** [comment]
(copied from 2020-05-argo_dbcp_programmes.docx)

**Conclusion and Recommendation**
It is recommended to add the entries suggested in this document to reflect the appropriate affiliation and credits to the operator of the observing facility.
Mathieu Belbéoch, as the Argo international technical coordinator, is working closely with the Argo experts to define these entries and thus they support these new additions.
Long Jiang, as the DBCP international technical coordinator, is working closely with the Argo experts to define these entries and thus they support these new additions.
These programme entries are defined by JCOMMOPS only, in order to work with the community. Hence, they do not create any conflict with the existing values.


Notation | Name | Path | Definition
-- | -- | -- | --
AtlantOSH2020 | AtlantOS_H2020 | \Co-sponsored\GOOS\Argo\AtlantOS_H2020 | Atlantic Ocean Observing   System Horizon 2020 Argo project
ARGOPeru | Argo PERU | \Co-sponsored\GOOS\Argo\Argo PERU | Argo project - Peru
ARGOUWSOCCOM | Argo UW-SOCCOM | \Co-sponsored\GOOS\Argo\Argo UW-SOCCOM | University of Washington - Southern   Ocean Carbon and Climate Observations and Modelling Argo programme
MOCCAEU | MOCCA-EU | \Co-sponsored\GOOS\Argo\MOCCA-EU | Monitoring the Oceans and   Climate Change with Argo – EU
MOCCAGER | MOCCA-GER | \Co-sponsored\GOOS\Argo\MOCCA-GER | Monitoring the Oceans and   Climate Change with Argo – Germany
MOCCAIT | MOCCA-IT | \Co-sponsored\GOOS\Argo\MOCCA-IT | Monitoring the Oceans and   Climate Change with Argo – Italy
MOCCANETH | MOCCA-NETH | \Co-sponsored\GOOS\Argo\MOCCA-NETH | Monitoring the Oceans and   Climate Change with Argo – Netherlands
MOCCAPOL | MOCCA-POL | \Co-sponsored\GOOS\Argo\MOCCA-POL | Monitoring the Oceans and   Climate Change with Argo – Poland
ARGONIMSKMA | Argo NIMS/KMA | \Co-sponsored\GOOS\Argo\Argo NIMS/KMA | National Institute of   Meteorological Science/Korean Meteorological Administration Argo programme
ARGOUWMBARI | Argo UW-MBARI | \Co-sponsored\GOOS\Argo\Argo UW-MBARI | University of Washington – Monterey   Bay Aquarium Research Institute Argo programme
ARGOUWTPOSEQ | Argo UW-TPOS eq. | \Co-sponsored\GOOS\Argo\Argo UW-TPOS eq. | University of Washington –   Tropical Pacific Observing System Argo equivalent programme
ARGOWHOISODAEQ | Argo WHOI-SODA eq. | \Co-sponsored\GOOS\Argo\Argo WHOI-SODA eq. | Woods Hole Oceanographic   Institution - Stratified Ocean Dynamics of the Arctic Argo equivalent   programme
ARGOMorocco | Argo Morocco | \Co-sponsored\GOOS\Argo\Argo Morocco | Morocco Argo programme
ARGOWHOIloopcurrentEQ | Argo WHOI-Loop Current eq. | \Co-sponsored\GOOS\Argo\Argo WHOI-Loop   Current eq. | Woods Hole Oceanographic   Institution - Loop Current, Gulf of Mexico Argo equivalent programme
EuroARGORISE | Euro-Argo RISE | \Co-sponsored\GOOS\Argo\Euro-Argo RISE | Euro-Argo Research   Infrastructure Sustainability and Enhancement project
ARGOFPAIIGMMC | Argo FPAII-GMMC | \Co-sponsored\GOOS\Argo\Argo FPAII-GMMC | Fondation Prince Albert   II de Monaco - Groupe Mission Mercator Coriolis Argo programme
NAVOCEANODBCP | Navoceano DBCP | \Co-sponsored\GOOS\DBCP\NAVOCEANO DBCP | Naval Oceanographic Office   DBCP programme
SAWSDB | SAWS DB | \Co-sponsored\GOOS\DBCP\SAWS DB | South African Weather   Service Drifting Buoys programme

**Comment by amilan17** [comment]
Branch: https://github.com/wmo-im/wmds/tree/issue-157

@anthoninlize - Can you verify that the updates are correct in the branch? https://github.com/wmo-im/wmds/blob/issue-157/tables_en/2-02.csv

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Can you verify that this branch is ready for Fast Track?

**Comment by joergklausen** [comment]
@amilan17 The newly added notations seem to be be inline with the spelling conventions (https://github.com/wmo-im/wmds/wiki/Guidance-for-spelling-of-notation), although AtlantOSH2020 is debatable.
@efucile I did notice that some of the existing notations violate the spelling conventions. While notations should not be interpreted as case-sensitive character strings, the spelling conventions were adopted to provide some consistency. Moreover, on the codes registry, the URI that is created uses upper and lower case. This is against the recommendations in support of good REST API design (Rule#5, https://blog.restcase.com/7-rules-for-rest-api-uri-design/).

My recommendation is to
- change all the URIs to lower-case-only to avoid confusion and potential hick-ups in using them.
- correct the lower-case spelling of 'germany', 'brazil' and possibly others to 'Germany', 'Brazil' etc.
- have @amilan17 go over the spelling of the notations in view of the adopted spelling convention.

NB: For OSCAR/Surface, there is not problem, as all terms are interpreted in a case-insensitive way.

**Comment by amilan17** [comment]
@joergklausen - This could be an improvement, but modifying all of these terms in the codes registry to comply with the REST API guidelines would be a significant change and it is out of scope for this current issue. The URIs in the codes registry are case sensitive and, therefore, simply changing the capitalization will break the URLs. Then, we'd need to establish redirects for everything that changed. While not impossible, it's definitely out of scope for these additions proposed in this issue.

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Can you confirm that the current changes are ready as they are (without sweeping revisions) for Fast-Track? 
https://github.com/wmo-im/wmds/tree/issue-157

**Comment by amilan17** [comment]
confirmed by @joergklausen that it is ready for FT.

**Comment by amilan17** [comment]
Approved by FT 2020-2
