### ISSUE TITLE
1-01-01 Atmospheric variables (lidar)

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#174]
Reported by Judd Welton:
Aerosol > Optical properties misses 'lidar defined backscatter', and 'single wavelength AOD'.
Aerosol > Physical proerties misses 'aerosol layer height'
Clouds > Position > Height of inversion is unclear. Is this PBL top? Definition required
Clouds > Type is unclear. Definition required

Missing 'PBL height' or 'mixed layer height'.

Overall, the observed variables for "lidar" are insufficient. Some other related variables are vague or inaccurate.

**Comment by markusfiebig** [comment]
This has been discussed also in the CF standard name vocabulary. There, "backwards scattering coefficient" refers to " the sum of scattering into all backward angles i.e. scattering_angle exceeding pi/2 radians". With this definition, the "particle backwards scattering coefficient" would be the property measured by an integrating nephelometer. In CF, the property measured by a lidar is called "backwards scattering function", since it depends on the scattering angle, which for a lidar of course is one angle. In the CF discussion, it was important to define variables in a way not depending on a specific method of observation. This makes sense for a vocabulary that is supposed to be generic, which is the case for WMDR as well.

**Comment by ejwelton** [comment]
I would like to close and remove this older issue from consideration. Instead, I will create new issues based on our recent WG-ACV discussions that specifically target requested changes to specific variables and creation of new ones.

**Comment by fstuerzl** [comment]
Expanded in issue #264, #265 and #266.
