### ISSUE TITLE
deal with special characters

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#18]
Table 3-02: Côte d'Ivoire is displayed as Cote d'Ivoire

Table 4-06: Sea
![image](https://user-images.githubusercontent.com/43061805/50824262-6975cb80-1336-11e9-9396-b111502cd17c.png)
displayed as  (zo ? 2). How can we correctly display zo?

@efucile How can we improve this?

**Comment by efucile** [comment]
I have just fixed Côte d'Ivoire in branch https://github.com/wmo-im/wmds/tree/issue18 
It was very simple. Just copy the correct caracter.

**Comment by efucile** [comment]
We don't have subscript in unicode. I suggest z0=0.0002. However it is not clear what z0 means in this context. I think that this needs a review by the team at a later stage as the text is not clear.
Please note that I made a branch for this specific issue. When this is solved we can merge to master and we can align development with master to avoid being behind. It is not correct to make this change in development because this is important for EC69 baseline.
I have also noted that table 4-06 in development branch is in asci format and with tab separator. This is wrong and needs to be changed.

**Comment by efucile** [comment]
I have also fixed the problem in the multilingual version of table 3-02

**Comment by HoratN** [comment]
I fixed encoding of 4-06 in the branch https://github.com/wmo-im/wmds/tree/issue18.

**Comment by nuneslf** [comment]
@HoratN @efucile Is there something still pending here, or could we close this issue?

**Comment by LuisaIckes** [comment]
I think this issue can be closed

**Comment by joergklausen** [comment]
Closed, I don't see what we could do to improve here.
