### ISSUE TITLE
1-02 Encoding of unit 'E' on wmo.codes.int/wmdr/unit

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#183]
The encoding of the entry http://codes.wmo.int/wmdr/unit/E is incorrect.
![image](https://user-images.githubusercontent.com/34302947/89518887-d8016080-d7db-11ea-9730-9572e9cdb284.png)

**Comment by fstuerzl** [comment]
**Summary and Purpose**
Label for entry "E" in Table "Units" is incorrectly encoded in Codes Registry (see [https://codes.wmo.int/wmdr/unit/E](https://codes.wmo.int/wmdr/unit/E))

**Proposal**
Correct encoding of label for entry "E" in Table "Units", so that it reads Eötvös instead of "EÃ¶tvÃ¶s".

**Reason**
Bug in encoding needs to be fixed

**Comment by amilan17** [comment]
this displays as expected on test. I think it's a simple update of prod to fix this. 
http://testwmocodes.metarelate.net/wmdr/unit/E

**Comment by amilan17** [comment]
@joergklausen - this is fixed
