### ISSUE TITLE
1-01-x Re-concile variable lists of OSCAR/Requirements with the official WMD codelists

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#190]
OSCAR/Requirements uses a list of variables that is not fully re-conciled with the official list of variables as found on codes.wmo.int/wmdr. Moreover, these variable also use numeric codes, but different numbers. Thus, not only are the entries partly different, but there is a risk that users may refer to a variable intended for machine-based metadata management in OSCAR/Surface from the list of OSCAR/Requirements. A concerted effort is needed to 
- review these code lists and 
- include well-defined variables from OSCAR/Requirements in case they are still missing in Table(s) 1-01-x
- update the notation in OSCAR/Requirements to use the same notation as used in Table(s) 1-01-x

john.eyre@metoffice.gov.uk is volunteering to help with this issue.

**Comment by fstuerzl** [comment]
The following tables contain [OSCAR/Requirement variables](https://www.wmo-sat.info/oscar/variables), which are missing in the WIGOS vocabulary (and not yet included in another issue).

OSCAR Requirements domain: **"Aerosol and radiation"**
->domain: Atmosphere,  new entries in table 1-01-01
|name|definition|
|--|--|
|Aerosol Optical Depth|The AOD is the effective depth of the aerosol column from the viewpoint of radiation propagation: Vertical column integral of spectral aerosol extinction coefficient AOD = exp(-K. Δz) where K is the extinction coefficient [km-1 ] and Δz the vertical path [km] |
|Aerosol species mole fraction|3D field of the mole fraction of condensed-phase chemical species (e.g., sulfate, nitrate, ammonium, elemental carbon, organic carbon),  in the atmosphere|
|Downward short-wave irradiance at Earth surface|Flux density of the solar radiation at the Earth surface |
|Downward short-wave irradiance at TOA|Flux density of the solar radiation at the top of the atmosphere |
|Earth surface short-wave bidirectional reflectance|Reflectance of the Earth surface as a function of the viewing angle and the illumination angle in the range 0.4-0.7 . The distribution of this variable is represented by the Bidirectional Reflectance Distribution Function (BRDF)|
|Long-wave Earth surface emissivity|Emissivity of the Earth surface in the thermal IR, function of the wavelength |
|Upward short-wave irradiance at TOA|Flux density of solar radiation, reflected by the Earth surface and atmosphere, emitted to space at the top of the atmosphere |
|Upward spectral radiance at TOA|Upward radiant power measured at the top of the atmosphere per area unit, per solid angle, and per wavelength interval. Spectral range 0.2-200 µm. Resolving power ?/??= 1000. Accuracy quoted as SNR (Signal-to-Noise-Ratio), actually SNR^-1 so that smaller figure means better performance, as usual. |
|Upward long-wave irradiance at TOA|Flux density of terrestrial radiation emitted by the Earth surface and the gases, aerosols and clouds ot the atmosphere at the top of the atmosphere |
|Aerosol single-scattering albedo| The spectrally dependent ratio of the aerosol scattering to the aerosol extinction |
|Aerosol Layer Height|Height of vertically localized aerosol layer in the free troposphere above sea level |
|Solar spectral irradiance|Total Solar Irradiance (TSI); when measured as a function of wavelength it is the spectral irradiance |
|Radiation profile|Vertical profile of upward and downward LW and SW radiation components|

OSCAR Requirements domain: **"Atmospheric chemistry"**
->domain: Atmosphere,  new entries in table 1-01-01

|name|definition|
|--|--|
|OH| 3D field of amount of OH (Hydroxil radical, expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles) |
|C10H16 (alfapinene) Mole Fraction|3D field of amount  of C10H16 (alfapinene,expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles).  |
|C10H16 (betapinene) Mole Fraction|3D field of amount of C10H16 (betapinene, expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles) |
|C10H16 (3-Carene) Mole Fraction|3D field of amount  of C10H16 (3-Carene, expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles) |
|C10H16 (Limonene) Mole Fraction|3D field of dry air mole fraction of C10H16 (Limonene, expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles).|
|(14)CO2 Delta|3D field of Delta C-14 in CO2 (Carbon dioxide) (isotopic signature)|
|C(18)OO Delta| 3D field of Delta O-18 in CO2 (Carbon dioxide) (isotopic signature)|
|(13)CH4 Delta| 3D field of Delta C-13 in CH4 (Methane) (isotopic signature)|
|(14)CH4 Delta| 3D field of Delta C-14 in CH4 (Methane) (isotopic signature)|
|CH3D Delta| 3D field of Delta Deuterium (H-2) in CH4 (Methane) (isotopic signature)|
|(13)CO Delta| 3D field of Delta C-13 in CO (Carbon monoxide) (isotopic signature)|
|(14)CO Number Concentration| 3D field of amount of CO (Carbon monoxide) with C-14 isotope (mol) per air volume (m3)|
|C(18)O Delta| 3D field of Delta O-18 in CO (Carbon monoxide) (isotopic signature)|
|N(15)NO Delta| 3D field of Delta N-15 in N2O (Nitrous oxide) (isotopic signature)|
|N2(18)O Delta| 3D field of Delta O-18 in N2O (Nitrous oxide) (isotopic signature)|
|C(17)OO Delta| 3D field of Delta O-17 in CO2 (Carbon dioxide) (isotopic signature)|
|CO Total Column| 2D field of total number of CO modelcues (Carbon Monixide) per unit area in an atmospheric column extending from the Earth's  surface to the upper edge of the atmosphere.|
|Glyoxal Mole Fraction| 3D field of amount of OCHCHO (Glyoxal, expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|(13)CO2 Delta| 3D field of Delta C-13 in CO2 (Carbon dioxide) (isotopic signature)|
|N(15)NO-Alpha Delta| 3D field of Delta N-15 in Alpha-N2O (Nitrous oxide where the outer Nitrogen atom is N-15)  (isotopic signature)|
|N(15)NO-Beta Delta| 3D field of Delta N-15 in Beta-N2O (Nitrous oxide where the middle Nitrogen atom is N-15) (isotopic signature)|
|CO2 Tropospheric Column|2D field of total amount of CO2 molecules per unit area in an atmospheric column extending from the Earth’s surface to the tropopause. |
|CO2 Mole fraction (SR)| 3D field of amount of  source region (SR) CO2 (Carbon Dioxide) (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|CO2 Mole fraction (BG)| 3D field of amount of  background (BG) CO2 (Carbon Dioxide) (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|CH4 Tropospheric column| 2D field of total amount of CH4 molecules per unit area in an atmospheric column extending from the Earth’s surface to the tropopause. |
|HD Delta| 3D field of Delta Deuterium (H-2) in HD (molecular Hydrogen) (isotopic signature)|
|NO2 Tropospheric column|2D field of total amount of NO2 molecules per unit area in an atmospheric column extending from the Earth’s surface to the tropopause. |
|CO Tropospheric column| 2D field of total amount of CO molecules per unit area in an atmospheric column extending from the Earth’s surface to the tropopause.  |
|HCHO Tropospheric column|2D field of total amount of HCHO molecules per unit area in an atmospheric column extending from the Earth’s surface to the tropopause. |
|Glyoxal Tropospheric column| 2D field of tropospheric column averaged of amount of Glyoxal (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|CH4 Mole fraction (BG)| 3D field of amount of  background (BG) CH4 (Carbon Dioxide) (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|CH4 Mole fraction (SR)| 3D field of amount of  source region (SR) CH4 (Carbon Dioxide) (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|NO2 Mole fraction (BG)| 3D field of amount of  background (BG) NO2 (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|NO2 Mole  fraction (SR)| 3D field of amount of Source Region (SR) NO2 (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|NO3 Mole Fraction| 3D field of amount of NO3 (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|
|N2O5| 3D field of amount of N2O5 (expressed in moles) divided by the total amount of all constituents in dry air (also expressed in moles)|

OSCAR Requirements domain: **"Basic atmospheric"**
->domain: Atmosphere,  new entries in table 1-01-01
|name|definition|
|--|--|
|Atmospheric temperature|3D field of the atmospheric temperature |
|Height of the tropopause|Height of the surface separating the troposphere from the stratosphere |
|Temperature of the tropopause|Atmospheric temperature at the height of the surface separating the troposphere from the stratosphere |
|Relative humidity|3D field of relative humidity in the atmosphere. Relative humidity is the ratio of the amount of atmospheric moisture present relative to the amount that would be present if the air were saturated with respct to water or ice to be specified in the metadata|
|Wind direction (near surface)|Direction from which wind is blowing at a known height above the surface which is to be specified in the metadata|

OSCAR Requirements domain: **"Solar monitoring"**
->domain: Outer Space,  new entries in table 1-01-02
|name|definition|
|--|--|
|UV flux spectrum|Energy spectrum of diffuse UV flux measured in space.|
|VIS flux|Integrated VIS flux|
|VIS flux spectrum|Energy spectrum of diffuse VIS flux measured in space|
|VIS sky image|VIS image of the sky|
|NIR/SWIR flux|Integrated NIR/SWIR flux|
|NIR/SWIR flux spectrum|Energy spectrum of diffuse NIR/SWIR flux measured in space|
|NIR/SWIR sky image|NIR/SWIR image of the sky|

**Comment by fstuerzl** [comment]
New document including all currently operational WIGOS variables: [variable_mapping_WMDR_OR_2021-11.xlsx](https://github.com/wmo-im/wmds/files/7521437/variable_mapping_WMDR_OR_2021-11.xlsx)
Variables added in FT-2021-2 have the status "new - to be mapped" and were not yet compared with the OSCAR/Requirements variables. This updated excel file can be used as the basis for work on this issue.

**Comment by JohnEyre** [comment]
Thanks, Franziska.
How would you like me to interact with this xlsx file? Should I just add more comments to the “Comments” column?
John

**Comment by fstuerzl** [comment]
@JohnEyre, if there are exact matches between O/R and WIGOS variables, I'd suggest, it is most convenient, if you move the WIGOS variable to same line that contains the corresponding O/R variable. Otherwise comments are fine of course.

**Comment by amilan17** [comment]
Elios Cloud version of the [XSL spreadsheet](https://elioscloud.wmo.int/share/page/site/tt-wigosmetadata/document-details?nodeRef=workspace://SpacesStore/ff11fa3e-a6b5-4419-b93b-985a175111f4#page=1)

**Comment by fstuerzl** [comment]
This issue will be split up into multiple sub-issues, which will be listed below later.

**Comment by JREyre** [comment]
@fstuerzl @joergklausen @amilan17 
This Issue is now rather old.  Some of the more difficult problems have been transferred to other Issues.  Others problems were raised at the JET-EOSDE Workshop in Sept 2022, and this resulted in Actions on several JET members.  I propose to await progress on these Actions and, if successful, then to recommend to you that we close this Issue.

**Comment by JREyre** [comment]
@joergklausen @amilan17 @fstuerzl 
I think all the issues that were originally raised under #190 are now complete or covered elsewhere.  Do you agree?  If so, can we close #190.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD) notes:

team agrees to close the issue;
