### ISSUE TITLE
Develop criteria and implementation for deprecate and supersede states of WIGOS terms

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#199]
**Decision**
https://github.com/wmo-im/wmds/wiki/Guidance-for-Removal-of-Terms

**Summary and Purpose** 
The Codes Registry is designed to provide immutable URLs to code values that users and systems can rely on. In general, we should never consider removing a term. However, sometimes it is important to no longer support a particular term for various reasons and we don't have a process in place to manage this for WIGOS Codes. 

**Proposal** 
1. Develop a criteria to consistently evaluate whether a term should be deprecated, superseded or remain unchanged. 
2. Identify the appropriate implementation of these states in the registry. 

**Merriam-Webster Definitions**
Deprecate: to withdraw official support for ~or discourage the use of in favor of a new or better alternative~
Supersede: to displace in favor of another

**Comment by tomkralidis** [comment]
For 2. implementation, suggest that codes.wmo.int supports versioning, so that deprecating and superceding is based on how many versions of a code list we support over time.

Example based on OGC [EPSG codes](https://www.opengis.net/def/crs/):
- list all versions: https://www.opengis.net/def/crs/EPSG
- use an EPSG code based on a specific codelist version
  - https://www.opengis.net/def/crs/EPSG/9.9/4326
  - https://www.opengis.net/def/crs/EPSG/8.9.2/4326
- always use the EPSG code based on the latest codelist version (`0` -- at user's own risk to changes)
  - https://www.opengis.net/def/crs/EPSG/0/4326

Given WMDR and WIS codelists are themselves versioned, this should be represented in their resulting deployment in the code registry, to be able to pin to a version accordingly.

**Comment by joergklausen** [comment]
In my understanding, 'supersede' is a possible, optional next logical step after 'deprecate'. We supersede a deprecated term with another one if there is a new one, we only deprecate if there is no replacement term. I am with @tomkralidis in supporting versioning, but I don't know if that is possible and when it would be implemented. In the meantime, I suggest we 'deprecate' terms in the registry if we do not want them anymore, we supersede terms if we have a replacement that we recommend. 
I suggest we include these attributes also in parentheses in the description.
Concerning OSCAR/Surface, we will remove such terms from our internal copy of the code lists if they are not used in any of the metadata records. We will add the attributes in parentheses if they are. We will also try to convince those who have used a (now) deprecated term to update their metadata. Finally, we will substitute superseded terms with the new ones if that makes sense, and remove the superseded terms from the internal codelists.
@amilan17, @tomkralidis Please confirm that you are in agreement with this approach, so that we can close this issue.

**Comment by tomkralidis** [comment]
+1

**Comment by amilan17** [comment]
@joergklausen @tomkralidis 

Thank you for your thoughts. I finally did some research on this today. I like the clarification that something can be deprecated and superseded at the same time. I suggest changing the terminology from deprecated to 'invalid' or 'retired' as appropriate for that code. 

Below is a summary of Code Registry Features and some use cases that we need to consider when determining.  

**Code Registry Status Values**

*   experimental - for new codes that have not been approved yet
*   invalid - code remains in registry, not visible to public, URL returns 404
    *   [http://testwmocodes.metarelate.net/annas_playground/4-04/EventAtFacility/_construction](o%09http:/testwmocodes.metarelate.net/annas_playground/4-04/EventAtFacility/_construction)
*   retired - code remains in registry, visible to public, URL returns code with retired status
    *   [http://testwmocodes.metarelate.net/annas_playground/4-04/EventAtFacility/corrosion](http://testwmocodes.metarelate.net/annas_playground/4-04/EventAtFacility/corrosion)
*   superseded - code remains in registry, visible to public, URL returns code, metadata provides link to the code that supersedes it
    *   must implement manually through UI
    *   [http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_260](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_260)

**Code Registry Actions** 

*   Edit and replace
    *   codes are added and updated programmatically from GitHub content, the UI actions are not used manually
    *   new codes get a status of 'experimental'
    *   status of updated codes do not change
*   Delete
    *   Not recommended: programmatic updates do not delete anything.  Results in hard removal of content and URL returns a 404. must be done manually.

**Use Cases** 

*   Code needs typographical edits or additional information to add and the notation does not change ==> edit 
*   Code needs updates and the concept remains the same, but edits will change the 'notation' that becomes part of the URL ==> supersede with new code
    *   E.g. #188
*   Code needs updates and the concept changes ==> keep code and create new code with new concept
*   Code is too broad and needs to be broken up into more precise terms ==> keep code, don’t supersede and create new more precise terms
    *   #187
*   Multiple codes are too narrow and needs to be broader ==> supersede multiples codes with one code
*   Two codes represent the same concept ==> supersede one of them
    *   e.g. #167
*   Code is obviously wrong or is an error and there is no substitute ==> change status to invalid
*   Code is no longer relevant and there is no substitute ==> change status to retired

**Comment by amilan17** [comment]
There is a version number associated with a registry and each code in that registry and this will change incrementally upon changes. I don't think it meets our use cases, however, there is an active discussion with Mark underway for him to understand the requirements and research options for supporting more robust versioning.

**Comment by joergklausen** [comment]
Thanks @amilan17, these reflections are useful. Regarding OSCAR/Surface, we would then append codes that are no longer valid and have no substitute with (retired) rather than the more generic (deprecated), right? We should not encounter the case (superseded), because we would substitute any superseded code value with the new one using DB operations. We would also hopefully be able to deal with any codes that are (invalid), so this should also not be needed in OSCAR/Surface.

On 4. Rather than keep code, these should also be retired, I think, to avoid the risk of continued use.

**Comment by amilan17** [comment]
@efucile - please review this decision tree and workflow.

**Comment by efucile** [comment]
@amilan17 this is very useful, and we should have it in the wiki as documentation for the team.
They all look good to me at the moment. What @joergklausen  says is in a sense a special use of the proposal. I don't have a strong opinion on 4. There are pro and cons in retiring a term in that case.

**Comment by amilan17** [comment]
*   [ ] add to wiki before closing this issue

**Comment by joergklausen** [comment]
In terms of practical work on the .csv files, @amilan17 and I agreed that retired terms should actually be removed from the .csv file, so that an eventual publication on the codes.wmo.int does not preserve them erroneously.

**Comment by amilan17** [comment]
[Guidance-for-Removal-of-Terms](Guidance-for-Removal-of-Terms)

**Comment by amilan17** [comment]
@RMaerz @joergklausen @gaochen-larc 

Please review wiki page for clarity, consistency and usefulness. 

https://github.com/wmo-im/wmds/wiki/Guidance-for-Removal-of-Terms

**Comment by gaochen-larc** [comment]
Please consider combining "multiple codes are too narrow and there needs to be broader term" and "two codes represent the same concept" to "multiple codes are too narrow or represent the same concept and there needs to be broader term"

If not, please consider change "two codes represent the same concept" to "Multiple codes represent the same concept"
