### ISSUE TITLE
Adjudicate code differences between GitHub and Codes Registry

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#206]
**Summary and Purpose**
Determine if there are differences between GitHub and Registry and how to fix if needed.

**Comment by joergklausen** [comment]
Hi Anna
Funny, when I click on https://github.com/wmo-im/wmds/issues/206 I don’t get to see the same text as in the mail message. The authoritative source was intended to be the Common code table C-6



COMMON CODE TABLE C-6: List of units for TDCFs
(Used only in Volume I.2, Part B and C)

Then a decision was made to separate the WMDR code list for units and add necessary element to it. The examples you provide are scary, because ‘S’ is ‘Siemens’, while ‘s’ is ‘seconds’. So these are totally different, and capitalization really matters. Are you going to cross-check??
Kind regards
Jörg

___________________
Dr. Jörg Klausen

Federal Department of Home Affairs FDHA
Federal Office of Meteorology and Climatology MeteoSwiss

Operation Center 1 | P.O. Box 257 | CH-8058 Zurich-Airport
Phone: +41 58 460 92 23
joerg.klausen@meteoswiss.ch<mailto:joerg.klausen@meteoswiss.ch> | Mobile: +41 79 702 94 67

All about weather and climate, please visit our website
www.meteoswiss.ch<https://www.meteoswiss.admin.ch/> and MeteoSwiss App<http://www.meteoswiss.admin.ch/home/services-and-publications/beratung-und-service/meteoswiss-app.html>

All about OSCAR/Surface at https://oscar.wmo.int/surface
All about GAWSIS at https://gawsis.meteoswiss.ch

**Comment by amilan17** [comment]
There are still a couple differences based on the last test results found under actions. 
https://github.com/wmo-im/wmds/runs/1431181655

1. The Registry has two versions of WaterML and one is set to invalid. Git has one which may have a different description. 
<img width="1035" alt="Screenshot 2020-11-20 at 15 39 51" src="https://user-images.githubusercontent.com/5168866/99812507-d5d2d000-2b46-11eb-8020-67e19c56d964.png">
Furthermore, there is a different reference to WaterML in the https://codes.wmo.int/wmdr/_QualityFlagSystem. This entry refers to the opengis instance instead. 

2. I don't understand the problem
![image](https://user-images.githubusercontent.com/5168866/99811887-09612a80-2b46-11eb-96f9-0db16fe971ab.png)

3. The test needs to recognize that values are case sensitive and these do NOT represent a mismatch between Git and Registry
- <http://codes.wmo.int/wmdr/unit/S>
- <http://codes.wmo.int/wmdr/unit/S_m-1>
- <http://codes.wmo.int/wmdr/unit/a>
- <http://codes.wmo.int/wmdr/unit/h>
- <http://codes.wmo.int/wmdr/unit/t> 
-

**Comment by amilan17** [comment]
fixed Quality Flag discrepancy. The test still doesn't recognise the differences between lower and upper cases, but this is only when comparing on the TEST registry. This error does not appear on prod.
