### ISSUE TITLE
2-02 Add RBON to supersede RBCN and RBSN

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#215]
**Branch**

new branch: https://github.com/wmo-im/wmds/tree/issue215-FT

old branch: https://github.com/wmo-im/wmds/tree/Issue-215

**Summary and Purpose**  
RBON has been approved by WMO and will supersede the existing RBCN and RBSN and subsets thereof.

**Stakeholder(s)**  
echarpentier@wmo.int

**Proposal**  
Add RBON under GOS, mark all RBCN and RBSN as superseded.

**Reason**  
RBON has already been approved by WMO. This is a formal change that is needed to follow procedures. WMO will also suggest how the procedures can be improved.

**Comment by IgorZahumensky** [comment]
Maybe good to consider GBON to be added as well; 
the GBON concept was approved by Cg-18; 
the draft GBON provisions were endorsed by INFCOM-1 to be submitted to Cg-Ext(2021).

**Comment by joergklausen** [comment]
Branch created at https://github.com/wmo-im/wmds/tree/Issue-215.
RBON added, the existing RBONpilot is marked as superseded.
GBON added, although this needs clear guidance from echarpentier@wmo.int.

**Comment by echarpent** [comment]
RBON entry in code table needs to be created since (i) we have corresponding Technical Regulations in the WIGOS Manual, and (ii) RA-III has already decided to merge their RBSN and RBCN stations into RBON. Other regional associations are now about to do the same.

However, it is premature to create an entry for GBON at this stage since Technical Regulations for GBON have not been approved by Congress yet (only recommended by INFCOM-I Part II) and there has been no concrete proposal on the initial GBON design yet.

**Comment by echarpent** [comment]
Further to my comment above, and in contrary to what I write, I'd finally suggest to create a GBON entry to allow for GBON initial design to be undertaken.
To simplify, it could well be named "GBON" instead of "GBON initial design".

**Comment by joergklausen** [comment]
Branch confirmed correct.

**Comment by echarpent** [comment]
For ANTON, the network is going to eventually be integrated into RBON as decided by Congress. Suggest status quo for now (i.e. no new entry for ANTON). When stations will be integrated in RBON, we'll link their observations to appropriate application area.

**Comment by amilan17** [comment]
The branch is not ready - the superseded terms need to be removed and added to the superseded.txt file.

**Comment by fstuerzl** [comment]
@amilan17 now, it's ready
