### ISSUE TITLE
new table 5-02

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#30]

**Comment by HoratN** [comment]
I added table 5-02 to the branch https://github.com/wmo-im/wmds/tree/issue30.

The methods in OSCAR are ordered like a tree. The extract which I uploaded only contains the 'endpoints' of the tree, so it doesn't contain 'method groups' like 'soil moisture'.

**Comment by ebuyukbas** [comment]
It may be better to use the term "parameters" instead of "methods" for the following branches 
* Table 5-02-01 contains the atmospheric methods (parameters)
* Table 5-02-05 contains the terrestrial methods (parameters)

On the other hand, I could not see the GPS based tracking for radisosonde. It is included in composite tarcking or not?

_330		\Atmosphere\Radiosonde with composite method tracking	Radiosonde with composite method tracking_

**Comment by nuneslf** [comment]
@ebuyukbas We need to close all the issues now (actually, this issue #30 has been closed last week) and we should export the new versions of code tables by Monday 25 February 2019, in order to submit them for the FastTrack procedure.
Therefore, the suggestion is to not introduce new entries to the tables at this point;
Only if you see an error in this or other tables, please just say so, and we will be corrected them, otherwise, further changes and improvements to the code tables should come at a later stage, either via feedback to this round of FastTrack consultation, or via a subsequent round (there are two rounds per year).
