### ISSUE TITLE
Table 1-02: New measurement unit "metre per year"

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#338]
# **Branch**
https://github.com/wmo-im/wmds/tree/issue338
# **Summary and Purpose**

The GCW Permafrost Task Team proposes to add “metres per year” as a new measurement unit under table 1-02.

The unit will be linked to the new permafrost variable “rock glacier velocity” (domain: terrestrial, tag: cryosphere).

# **Proposal**

Add “metre per year” to the measurement units in table 1-02.

<html><body>

Name | Notation|Description
-- | --|--
metre per year | m.a-1|  Conventional unit of velocity. 

</body>
</html>

Link the new unit to the variable “rock glacier velocity” (domain: terrestrial, tag: cryosphere).

# **Reason**

The new variable “rock glacier velocity” has been submitted to the WIGOS Task Team. The variable is measured and reported in the unit “metres per year”. The unit needs to be added to table 1-02 in order to be linked to the new variable.

# **Stakeholder(s)**

GCW Permafrost Task Team:

*   Anna Irrgang (anna.irrgang@awi.de)
*   Jeannette Nötzli (jeannette.noetzli@slf.ch)
*   Philippe Schoeneich (philippe.schoeneich@univ-grenoble-alpes.fr)
*   Ketil Isaksen (ketil.isaksen@met.no)
*   Andrea Merlone (a.merlone@inrim.it)
*   Graziano Coppa (g.coppa@inrim.it)
*   Charles Fierz (fierz@slf.ch)
*   Rodica Nitu (rnitu@wmo.int)
*   Nora Krebs (nkrebs@wmo.int)
*   Lauren Derby (lderby@wmo.int)

# Consultations
GCW Letter to the Permafrost Community shared with the Permafrost Carbon Meeting
@meulenvd 

# Context

https://www.bipm.org/en/publications/si-brochure

# Expected Impact of Change
MEDIUM

**Comment by amilan17** [comment]
related to: #337

**Comment by joergklausen** [comment]
Correct notation, description added:
<html><body>


Name | Notation|Description
-- | --|--
metres per year | m.a-1|SI derived unit of velocity, approximately equal to 3.168 874E-8 m.s-1 (for a Gregorian year of 365.2425 days)

</body>
</html>

@amilan17 Please create branch.
@fierz @rnitu Please confirm branch once established.

**Comment by rodicanitu** [comment]
Correspondence from Anna Irrgang (GTN-P) on 8 Nov 2021:
1) confirm that the most recent description you suggested for the active layer thickness works well for me.
2) GCW Letter to the Permafrost Community shared with the Permafrost Carbon Meeting on Nov. 16-18th.  if there will come any input/comments from the permafrost community than it might come after November 18th.
3) Actually coming back to the definitions I would like to inform you that the 0 deg C definition for permafrost will be (still) applied in the new GTN-P Strategy and Implementation Plan (SIP). The SIP will be released next week during the GTN-P National and Young National Correspondents meeting. We cannot hold the SIP back any longer (it is meant to be for 2021-2024!), so this definition will continue to be applied for the GTN-P.

18.11.2021 update (R Nitu): confirmation  deferred  to 26 Nov.

**Comment by amilan17** [comment]
\[Meeting 16 notes\](https://github.com/wmo-im/wmds/wiki/2021-11-18-TT-WIGOSMD-16):

*   Jitze, confirm that "SI derived unit of velocity" is consistent with SI. If not, then change description.

**Comment by meulenvd** [comment]
> [Meeting 16 notes](https://github.com/wmo-im/wmds/wiki/2021-11-18-TT-WIGOSMD-16):
> 
> * Jitze, confirm that "SI derived unit of velocity" is consistent with SI. If not, then change description.

The official SI system, published in https://www.bipm.org/en/publications/si-brochure defines velocity in terms of {L}/{T} = m/s because s is the (only) base SI unit for second. Apart from that, minute (min), hour (h) and day (d) are **accepted** as non-SI units with clearly defined  relationships, like 1 d = 24 h = 86 400 s. So "s" is a _base_ unit, the others are _derived_ units. Year or the unit "a" is not defined at all. To my opinion in WMO publications **non-accepted non-SI units** should be indicated as such and with an informative note en relation with an SI unit (there are many, e.g. 1 bar for 1 hPa). See for an interesting statement on the unit for year webpage https://usma.org/si-unit-definitions at the bottom.
Nevertheless some sci. unions need the use of long time periods expressed in years, like the international astrononical union IAU. So, they have defined a number of "Non-SI units that are recognised **for use in astronomony**", see table 5 on https://www.iau.org/publications/proceedings_rules/units/. The Year is defined as "year (**Julian**)" with unit "a" and defined 1 a = 31.5576 Ms = 365.25 d. Note that this **differs** from the above relation for a **Georgian** year with 1 a = 365.2425 d. So the use of the unit "a" is not everywhere the same and might give confusion or an unexpected extra measurement uncertainty. 
So, In principle we may not say in the description line "SI derived unit of velocity" but like IAU, "Non-SI unit that is recognized **for use in meteorology**".   
Note: the use of the Fortran/IBM notation like 3.168 874E-8 is not internationally recognized but used in practice by many instances. It may not lead to confusion, but is not in line with the notation practices, recommended by the sci. community (ICSU). WMO-No. 8 advices on the appropriate notations.

**Comment by joergklausen** [comment]
The current definition of [year](http://codes.wmo.int/wmdr/unit/a) defines a year as a unit of time with 31536000 s. This is neither Julian, nor revised Julian, nor Gregorian, but equal to 365 days. This is inconsistent and we should settle on one or the other. For the application at hand, the exact duration of a year is not relevant, so I am going to remove this and the reference to SI from the definition.

**Comment by gaochen-larc** [comment]
@joergklausen @amilan17  I checked unidata UDUNITS, there are several year definition.  The 365 day definition is consistent with "common year".   There are several similar terms:

sidereal_year: unit of time for the earth to make one complete revolution around the sun, relative to the fixed stars

tropical_year: unit of time; Interval between 2 successive passages of sun through vernal equinox (365.242198781 days). See http://www.ast.cam.ac.uk/pubinfo/leaflets/, http://aa.usno.navy.mil/AA/, and http://adswww.colorado.edu/adswww/astro_coord.html

year: unit of time; Interval between 2 successive passages of sun through vernal equinox (365.242198781 days). See http://www.ast.cam.ac.uk/pubinfo/leaflets/, http://aa.usno.navy.mil/AA/, and http://adswww.colorado.edu/adswww/astro_coord.html

common_year: unit of time corresponding to a 'normal' calendar year (365 days), that is, one without insertion of a leap day

leap_year: unit of time corresponding to a calendar year with a leap day inserted

Julian_year: unit of time recognized by the International Astronomical Union for use in astronomy, defined as 365.25 days of 86400 seconds

Gregorian_year: unit of time based on the Gregorian Calendar, the one commonly used today; approximates the tropical year as 365 + 97/400 days

**Comment by joergklausen** [comment]
@gaochen-larc Thanks also for pulling out the definitions of year. I am inclined to use Julian year, mostly because Julian day is a fairly common way of enumerating days and approximates the 'real' Earth year pretty well. But I think we should make the definition of year (the unit 'a') a separate issue in github.

@amilan17 Could you do this for us?

**Comment by amilan17** [comment]
> For the application at hand, the exact duration of a year is not relevant, so I am going to remove this and the reference to SI from the definition.

@joergklausen: I updated the proposal, an alternative definition could be "unit used to measure very slow velocities"

@rodicanitu @NoraCryo 

Please provide feedback on the updated definition. If there is a lot more discussion on this unit, we may not be able to submit it during FT2022-1. Will this have an impact on your implemenation?

**Comment by joergklausen** [comment]
Let‘s drop ‚glaciology‘ to be more generic: ‚Conventional unit of velocity.‘ I agree, this should be settled soon.

**Comment by rodicanitu** [comment]
@joergklausen @amilan17:  I agree with the definition "Conventional unit of velocity" and the use of "metre per year" . The community has expressed no concerns, so far. i think we should be ready to wrap up this item.

**Comment by amilan17** [comment]
@joergklausen please validate branch

**Comment by meulenvd** [comment]
For this unit, the specific year may not be relevant, de definition based on the Gregorian_year, defined as a constant, i.e. 365.2425 mean solar days = 3.1556952E7 s is best practice.  (However, it differs from the current constant  in Table 1-02 with 1 a = 31536000 s.)
This is in line with WMO-No. 1160 (Man. WIGOS): The time units used in processing (e.g. climatological) data should be selected from the following: (a) The Gregorian calendar year; (b) The months of this calendar; (c) The mean solar day, from midnight to midnight, according to the zonal time or the mean solar time of the station, when the data permit.
However, many published climatological records present yearly averages based on a Jan-1 00:00 to Dec-31 24:00 UTC scheme (so based on 365.00 or on 366.00 days for leap years), introducing an expanded uncertainty of about 0.6 day (or 0.16 %) or 5E5 s. This is relevant when using yearly records, but is irrelevant here, because this unit is associated to a pure intensity quantity, regardless to a specific period.
See further [1-02 Measurement Unit: Improve definition of year, issue #365](https://github.com/wmo-im/wmds/issues/365#)
