### ISSUE TITLE
1-02 Measurement Unit: Improve definition of year

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#365]
# **Summary and Purpose**

The current definition of [year](http://codes.wmo.int/wmdr/unit/a) defines a year as a unit of time with 31536000 s. This is neither Julian, nor revised Julian, nor Gregorian, but equal to 365 days. This is inconsistent and we should settle on one or the other. For the application at hand, the exact duration of a year is not relevant, so I am going to remove this and the reference to SI from the definition.

# **Proposal**

~ 9 June 2022

Redefine unit for year as "Conventional unit of time ranging from 365 days to 366 days".

<table><tbody><tr><td><strong>Notation</strong></td><td><strong>Name</strong></td><td><strong>Description</strong></td></tr><tr><td><strong>a</strong></td><td>year</td><td>Conventional unit of time duration, ranging from 365 days<s>, equivalent</s> to 366 days<s>31536000 s</s></td></tr></tbody></table>

# **Reason**

Improve definition by removing inconsistency in previous definition, which was invalid for leap years.

# **Stakeholder(s)**

\[include names and emails or handles of individuals or groups that introduced the proposal\]

# Consultations

@meulenvd  
@fierz  
@joergklausen

# Context

*   Manual on the WIGOS (2019 ed.)
*   WMO-No. 49, Vol. I (2011 ed.)

Being pragmatic the task team decided to keep the definition ambiguous and not distinguish between gregorian and julian year by specifying an exact amount of seconds.

# Expected Impact of Change

LOW

**Comment by amilan17** [comment]
see overview of different year definitions

https://github.com/wmo-im/wmds/issues/338#issuecomment-981210283

**Comment by gaochen-larc** [comment]
This issue will also impact the unit code list.  A related issue is "month" which is in the unit code list.

**Comment by fierz** [comment]
@gaochen-larc @joergklausen 
I support following the Julian year definition by IAU (a = 365.25 d). I think this is the value also used to compute the position of the sun, that is, quite relevant for radiation measurements and computations.

@gaochen-larc : "month" is indeed a tricky one. Non-SI for sure, with no properly defined value. Is it really needed as it does not appear in any other unit on the list?

**Comment by gaochen-larc** [comment]
> @gaochen-larc @joergklausen I support following the Julian year definition by IAU (a = 365.25 d). I think this is the value also used to compute the position of the sun, that is, quite relevant for radiation measurements and computations.
> 
> @gaochen-larc : "month" is indeed a tricky one. Non-SI for sure, with no properly defined value. Is it really needed as it does not appear in any other unit on the list?

I agree with Julian year also.

**Comment by gaochen-larc** [comment]
> @gaochen-larc : "month" is indeed a tricky one. Non-SI for sure, with no properly defined value. Is it really needed as it does not appear in any other unit on the list?

I was wondering if we need "month".  But I will do some more homework.

**Comment by joergklausen** [comment]
The ambiguity with month is simply a fact. I would not include it if it is not in the list already, otherwise a definition could be "conventional unit of time duration of between 28-31 days whereby 12 months amount to one year."

**Comment by gaochen-larc** [comment]
> The ambiguity with month is simply a fact. I would not include it if it is not in the list already, otherwise a definition could be "conventional unit of time duration of between 28-31 days whereby 12 months amount to one year."

We did have month as a unit, I am putting your description above in the table for now.

**Comment by meulenvd** [comment]
In the 2011 edition of the Technical Regulations (TR), Vol. I (WMO-No. 49; Vol. I; 2012), the year was defined under _Climatology_ (*). Chapter and definition were not regarded during the rigorous update in 2015 (because of WIGOS) so disappeared and not moved either to the Manual on the WIGOS (WMO-No. 1160). However, the Chapter in the **Manual on the WIGOS (2019 ed.)** now contains the same definition, but under _Hydrology_ (copied  from the TR, Vol. III, Hydrology). It states:

_7.4.1.6 Members should select the time units used in processing hydrological data for international exchange from the following:
(a) The **Gregorian** calendar year;
(b) The months of this calendar;
(c) The mean solar day, from midnight to midnight, according to the zonal time, when the data permit;
(d) Other periods by mutual agreement in the case of international drainage basins or drainage basins in the same type of region._

So this differs from the Int. Astronomy Union: year (**Julian**), unit a, 31.5576 Ms = 365.25 d, with  the astronomical unit of time is 1 day (d) of 86,400 SI seconds (s) (SI is the International System of Units). Note that the start (time stamp) of a Gregorian year differs from the start of a Julian year. I think it's up to ICSU or Unesco to make a statement on this definition.
_  _
(*) definition in WMO-No. 49, Vol. I (2011 ed.)
_1.4.1 Time units
The time units used in processing climatological data should be selected from the following:
(a) The **Gregorian** calendar year;
(b) The months of this calendar;
(c) The mean solar day, from midnight to midnight, according to the zonal time or the mean solar time of the station, when the climatological data permit._

**Comment by meulenvd** [comment]
The unit for year (a) may be used for a Lulian_year ( 1 a  = 365.25 d = 31536000 s) or a Gregorian_year (1 a = 365.2425 d or 365 days, 5 hours, 49 minutes and 12 seconds = 31556952 s. The difference is 20952 s (only **0.066 %**).  Taking into account this neglectable difference it is not relevant at all what to choose for. However, taking into account requirements in the Manual on the WIGOS (WMO-No. 1160) and earlier statements in the Technical Regulations (Gregorian Year, see above) it will be best practice to choose for the duration of the Gregorian year (**1 a = 31556952 s**) accepting that the duration of a Julian Year (31536000 s) is also used in practice.
A point of interest is that many published climatological records present yearly averages based on a Jan-1 00:00 to Dec-31 24:00 UTC scheme (so based on 365.00 days or on 366.00 days for leap years), introducing an expanded uncertainty of about 0.6 day (or **0.16 %**) or 5E5 s. This is relevant to consider when using yearly records, but is irrelevant when the unit a is associated to a pure intensity quantity, like metre per year regardless a specific period.

**Comment by gaochen-larc** [comment]
I vote for 365.25

**Comment by fstuerzl** [comment]
Summary and branch are updated.

**Comment by meulenvd** [comment]
'conventional unit of time ranging from 365 days to 366 days' as proposed by @amilan17 is a pragmatic solution, although some applications areas may object (climatology, hydrology, who follow their own). This definition introduces an uncertainty, i.e 1 a = 365.5 d +/- 0,5 d, so U = 0,5 d or U% = 0,5/365,5 = 0,14%. Considering that most of derived observable quantities, based on a yearly accumulation amount (precipitation, evaporation) have a significant larger measurement uncertainty, this uncertainty should be considered as acceptable.

**Comment by fierz** [comment]
I like and fully support the pragmatic approach that allows to use the 'appropriate' value depending on the use case, e.g. 365.25 to compute the sun position, notwithstanding others preferences. It nicely fits to the approach for [month ](https://github.com/wmo-im/wmds/issues/365#issuecomment-986538259)proposed by @joergklausen above.

**Comment by joergklausen** [comment]
It looks like we have consensus. @fstuerzl Please create branch. Once I am tagged to review the branch, I will and confirm.

**Comment by fstuerzl** [comment]
@joergklausen, here's the link to the branch: https://github.com/wmo-im/wmds/blob/issue365/tables_en/1-02.csv

**Comment by amilan17** [comment]
ready for FT
