### ISSUE TITLE
Request for qualifier to be added: Relative Humidity (%)

### ISSUE THREAD

**Issue by rnagarjun** [wmo-im/wmds#381]
# Proposal Summary

## **Summary and Purpose**

We are working with our network operators to upload station metadata into [OSCAR/SURFACE](https://oscardepl.wmo.int/surface/#/management/registerStation). One of the elements that station observes is Relative Humidity (%). Currently, we noticed Humidity([251](http://codes.wmo.int/wmdr/ObservedVariableAtmosphere/_251)) is available; However, it does not specify if it's relative or absolute. We would like a qualifier added to the element to indicate both.

## Proposal

_last update: 31 May 2022_

**Add codes for "Relative humidity" and "Specific humidity"**

<table><tbody><tr><td><strong>Notation</strong></td><td><strong>Name</strong></td><td><strong>Description</strong></td></tr><tr><td>12249</td><td>Relative humidity (with respect to water)</td><td>The ratio of the amount fraction of the water vapour in the air to the corresponding amount fraction if the air were saturated with respect to water at a particular pressure and temperature. Relative humidity is typically reported in percent (%). [Based on definition of R1490 in International Vocabulary of Meteorology (WMO-No. 182). 1992.]</td></tr><tr><td>12250</td><td>Specific humidity</td><td>The ratio of the mass of water vapour in the air to the mass of a moist air parcel, where the mass of the moist air parcel is the sum of the mass of water vapour and the dry air. Synonym: Moisture content. [Based on definition of M1750 in International Vocabulary of Meteorology (WMO-No. 182). 1992.]</td></tr></tbody></table>

**Supersede "Humidity (at specified distance from reference surface)" with new code 12249.**

| **Notation** | **Name** | **Description** | **Supersede by** |
| --- | --- | --- | --- |
| **251** | Humidity (at specified distance from reference surface) |   | Relative humidity (with respect to water) with notation of 12249 |

## **original request**

Requesting the following qualifier be added to [WMO code registry](http://codes.wmo.int/wmdr/ObservedVariableAtmosphere)/Element List.

*   Relative Humidity (%) - The ratio of the partial pressure of water vapor in an air-water mixture to the saturated vapor pressure of water at a prescribed temperature.

## **Stakeholder(s)**

@thineshsornalingam - OSCAR/Surface Focal Point (Canada)

## Consultations

WMO No. 182 (Meteorological Vocabulary), WMO No. 8 (GIMO), IPCC AR5

## Expected Impact of Change

HIGH

**Comment by gaochen-larc** [comment]
Should we also consider relative humidity over ice?  specific humidity is another frequently used term: the (dimensionless) ratio of the mass of [water vapor](https://glossary.ametsoc.org/wiki/Water_vapor) to the total mass of the system (AMS definition)

**Comment by fstuerzl** [comment]
@rnagarjun, I'm not sure I understand the proposal correctly. Do you suggest a name change for this variable
|notation|name|definition|
|-|-|-|
|251|Humidity (at specified distance from reference surface)||

to "Relative Humidity (%)" or the addition of a new variable?

|notation|name|definition|
|-|-|-|
|new id|Relative Humidity (%)|The ratio of the partial pressure of water vapor in an air-water mixture to the saturated vapor pressure of water at a prescribed temperature.|.

In the second case, I think, the expected impact is rather high than low! We need to assume, that OSCAR/Surface users have selected "Humidity (at specified distance from reference surface)" both for absolute and relative humidity, so a variable migration will be complicated. Also the WDQMS already refers to variable 251 as "Relative humidity" (see: https://wdqms.wmo.int/nwp/land_surface/six_hour/availability/humidity/all/2022-04-25/18) , so the current use of this variable is inconsistent.

**Comment by gaochen-larc** [comment]
AMS definition for relative humidity:  The ratio of the vapor pressure to the saturation vapor pressure with respect to water.
https://glossary.ametsoc.org/wiki/Relative_humidity

**Comment by rnagarjun** [comment]
@fstuerzl Our request is indeed the second one. We understand the complication involved in addressing this request. 
However, As you have indicate, the current use of this variable is inconsistent - which makes it difficult for users to differentiate between relative and absolute humidity. This is precisely the concern brought up by our network operators.

**Comment by JohnEyre** [comment]
AMS definition preferred to the current proposal - "air-water mixture" gives the wrong impression - air normally contains water vapour (dry air does not).
Prefer WMO (AngloEnglish) spelling of "vapour".

**Comment by gaochen-larc** [comment]
agree with @JohnEyre.  We should use the proper spelling to be consistent with the other documentation.   I would like raise the need to have relative humidity over ice.  I do understand it is much less widely used.  However, this may be a good opportunity to cover our bases.  For the same reason, we may also consider specific humidity and mixing ratio.  I am fine if we can consider these terms later.  Thanks!

**Comment by meulenvd** [comment]
I prefer like @JohnEyre, the use of vapour, not water. Relevant is that we deal with gaseous H20, not air containing aerosols. 
The definition adopted in the past by Cg is given in WMO-No. 8, Vol. I, Chap4 (humidity): Relative humidity U : Ratio in per cent of the observed vapour pressure to the saturation vapour pressure with respect to water at the same temperature and pressure; the term “relative humidity” is often abbreviated to RH.
Other parameters, associated to humidity are stated here too and also Cg adopted formulas to be used. More over in WMO-No. 180, WMO Meteorolgical Tables, based on the well known Smithonian Steam tables, and base for the formulas used in upper air dynamics, defines humidity variables accordingly. Note that WMO uses dewpoint, also for temperatures far below freezing point (so water). Icepoint is defined, but not recommended to aoid confusion. For that reason 'water' is used in the definition of RH.

**Comment by amilan17** [comment]
1.  For consistency with other codes, I agree with using "vapour" (http://codes.wmo.int/ui/text-search?query=vapour vs [http://codes.wmo.int/ui/text-search?query=vapor)](http://codes.wmo.int/ui/text-search?query=vapor))
2.  Please consider using definitions from the International Glossary for Hydrology (https://library.wmo.int/doc_num.php?explnum_id=8209)
3.  at a minimum, we should add a definition to 251.

**Comment by joergklausen** [comment]
My 5 cents, attempting to consolidate:
1. Spelling will be 'vapour'
2. 'Humidity (at specified distance from reference surface)' vs 'Relative humidity'. I am fairly convinced that the interpretation of WDQMS that these refer to the same quantity are justified. Hence I would support a process of superseding the existing variable 251 with 'Relative humidity'. The alternative is indeed to introduce one or several new variables and to deprecate the exsting 251. ***Action**: TT-WIGOSMD to decide on 2022-05-19*
3. The definition 1204 from the IGH is a bit convoluted, and it uses strange terminology, namely 'gram-molecular weight'. The UN Vocabulary (unterm.un.org) provides another more succinct definition, with a reference to IPPC AR5 (https://unterm.un.org/unterm/display/record/wmo/na?OriginalId=37d3bcc9-e882-4fec-bb75-91eefa951848): "**the ratio of actual water vapour pressure to that at saturation with respect to liquid water or ice at the same temperature**". The International vocabulary of Meteorology (WMO 182, https://library.wmo.int/doc_num.php?explnum_id=4712) is a bit dated, but provides definitions for both, relative humidity of moist air with respect to ice (R1480) and relative humidity of moist air with respect to water (R1490). These are identical except for the reference to ice or water: "*The ratio of the mole fraction of the water vapour in the air to the corresponding mole fraction if the air were saturated [with respect to ice][with respect to water] at a particular pressure and temperature*". I would prefer to define the term 'Relative humidity' as "**The ratio of the mole fraction of the water vapour in the air to the corresponding mole fraction if the air were saturated at a particular pressure and temperature**". Why? If we were to specify water vs ice in the definition, we really need 2 variables. This would be totally useless for our purposes, because most of the observations are made with commerical sensors, and the users don't even know how they are calibrated by the manufacturer. If the reference to water vs ice is really of importance, it can be specified elsewhere. ***Action** : TT-WIGOSMD to decide on 2022-05-19*

**Comment by gaochen-larc** [comment]
Agree with @joergklausen.  Also would like to add a point: humidity, e.g., specific humidity, or water vapor mixing ratio (equivalent to partial pressure) can be directly measured these days.   RH would need two measurements:  water vapour measurement and ambient temperature measurement.  The latter is to calculate the saturation vapour pressure or mole fraction.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22](https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22) notes: 

*   define relative humidity without ice, because we don't have an official request for RH over ice, based on WMO-No. 182
*    supersede 251 with new code for RH
*   consult with GCOS
*   open new issues to address 'mass mixing ratio' and clean up of other humidity related codes (this should be associated with the gap analysis)

**Comment by meulenvd** [comment]
Relevant to notice I think is that RH is a ratio and is dimensionless. It depends on what dimensions are used to generate the ratio (pressure, mass, volume?). It'sall explaned in WMO-No. 8, Vol. I, Chap4 (humidity), and with definition: Relative humidity U : Ratio in per cent of the observed vapour pressure to the saturation vapour pressure with respect to water at the same temperature and pressure; the term “relative humidity” is often abbreviated to RH. This definition is estblished already for a long time (also w/r ice) and I will not recommend to change it. Other Humidty related variable are in practice (mass mixing ratio, volume mixing ratio) and also dimensionless but usually the original units are provided (mg/kg). It must be noticed that, because RH is a derived variable (in fact a parameter), it must be reported with air temperature to make sense. 
Note that atmospheric pressure is relevant too (in association with moist air), where the vapour pressure of liquid aerosols apart from the gaseous vapour pressure has impact (see WMO-No. 8, Vol. I, Chap4 (humidity))

**Comment by amilan17** [comment]
I don't think this will be ready for FT22-2

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23](https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23) notes: 

*   team accepts proposed definitions, except for RH, change 'mole fraction' to 'amount fraction'
*   @amilan17 update the branch and tag @joergklausen when done

**Comment by amilan17** [comment]
@joergklausen @gaochen-larc please branch and issue summary are updated. Please review

**Comment by gaochen-larc** [comment]
The updated version looks great!  Thanks!

**Comment by amilan17** [comment]
ready for fT
