### ISSUE TITLE
Add variable for fog to table 1-01-01

### ISSUE THREAD

**Issue by SalomeKruger** [wmo-im/wmds#387]
# Proposal Summary

## **Summary and Purpose**

The measurement of fog as a type of precipitation does not appear in the code list, and should therefore be added.

## **Proposal**

Variable name: Fog  
Domain: Atmosphere  
Tags: Precipitation, Type of precipitation

## **Reason**

In meteorology, fog is seen as an obstruction to vision, but from an ecological/biological standpoint, it has a different meaning. Fog along the Namibian coast is seen as an important contributor to water for the survival of plants and animals. Therefore, fog is measured as a type of precipitation (in mm) throughout the year. Adding Fog as an additional variable will be a good idea.

## **Stakeholder(s)**

Ministry of Agriculture, Water & Land Reform  
Salome.Kruger@mawlr.gov.na

## Consultations

John Eye, Jitze van der Meulen

## Context

Guide to Instruments & Methods of Observation. 2018. WMO, Vol. 1 - Measurement of meteorological variables, point 6.6.3

## Expected Impact of Change

Low

**Comment by JohnEyre** [comment]
@joergklausen 
Fog is a type of cloud, i.e. cloud with the cloud-base at the surface.  So the existing variables containing the word "cloud" (there are 11 of them) are all potentially relevant here.
Fog has an impact on visibility, and this is one of the main reasons for observing it.  However there is an existing variable for visibility.
The main intention behind this proposal appears to be related not to fog as a cloud in the atmosphere but to the precipitation of fog at the surface.  In this case, it should be observed as precipitation.  We currently have 5 variables for precipitation: amount of ..., duration of ..., intensity of ..., occurrence of ..., type of ... .  [It may be better if "precipitation" were the first word in the variable name in each case.]

**Comment by joergklausen** [comment]
I agree with your analysis @JohnEyre . To me the question is whether a distinction between 'amount of precipitation' and 'amount of precipitation from fog' is relevant for the user, in which case we might agree to add the latter as a separate variable. It would be interesting if @SalomeKruger could expand on this herself.

**Comment by SalomeKruger** [comment]
@joergklausen and @JohnEyre I agree with the 'amount of precipitation from fog'. This just makes more sense,

**Comment by SalomeKruger** [comment]
@JohnEyre , that will be great since the same weather stations also have rain gauges to measure the 'amount of precipitation from rain.

**Comment by RMaerz** [comment]
This is indeed an interesting discussion and all arguments sound logical. let me add what comes in my mind.  Modern automated stations - and they will be common - can determine the rate of precipitation, the visibility and if an appropriate sensor is installed the type of precipitation by measuring the spectre of drop diameters. Usually precipitation from fog is from coagulation rather than sublimation over the ice phase and of smaller diameter of the drops. therefore typically of a low rate (per hour or minute) and often hard to be determined i.e. by tipping or weighing buckets. Taking into account that rate of precip and visibility can be analyzed to decide wether it could be from fog so it is also difficult  if we have a higher rate or higher visibility.  There is a full bandwith and precip intensity in fog can be increased if we have a higher elevated station in clouds where a 'nimbostratus' cloud extends several vertical kilometers causing heavier precipitation even if we have fog at the same time.  My personal conclusion is: often hard to decide if it's pure precip from fog or a mixture with 'classical' process over the ice phase.  If the sensors allow 'present weather' it can be reported in form of 'drizzle'  , and if  there is low visibility in the same report there should be enough evidence

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22](https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22) notes: 

*   still under discussion, it's really about precipitation, possible variable name: "amount of precipitation from fog"
*   @SalomeKruger - are you ok if we don't do this and only add the method? We think that you can achieve what you need by using the code "amount of precipitation" in combination with the "fog collection" method.

**Comment by JohnEyre** [comment]
@SalomeKruger @amilan17 @joergklausen .  We have agreed to proceed with #388 as an addition to observing technologies.  I am still not convined that we need "amount of precipitation from fog" as a variable separate from "amount of precipitation".  I could be convinced, if someone could show me that there is an APPLICATION that needs to distiguish between precipitation from fog and from other sources.  At our recent meeting, we guessed that agricultural meteorology may be such an application, and if so they should be consulted (via the RRR process), but I can't see why an agricultural meteorologist would need to know that the precipitation has come from fog (rather than from all sources).  Alternatively, is it necessary to add "amount of precipitation from fog" as a variable in order that we can proceed with #388?

**Comment by joergklausen** [comment]
We can proceed with #388, and I agree with @JohnEyre. I am also reluctant to add a specific variable unless clearly needed.

**Comment by meulenvd** [comment]
In the area of precipitation types (also w/r obstruction to vision) we have the type _drizzle_ too (reported as present weather). The variable Precipitation Intensity (the downward vertical component of moving droplets) is by definition only quantified if PI > 0.1 mm/h. If it's less than it is called 'trace'. I presume it's relevant that we are clear on the difference between drizzle and precipitation from fog.

**Comment by joergklausen** [comment]
@meulenvd I am not convinced that this difference is relevant for the use case at hand. As far as I understand this request, the interest is simply in the amount of water/precipitation that hits the ground and is available for plants to grow in the end. The circumstances are apparently such that fog is a predominant source of precipitation, hence the interest in it. As we have stated earlier, the 'method of observation' can be used to distinguish between precipitation that is collected as droplets falling down due to gravity and fog. Both are absorbed by the soil, eventually. In the WIGOS metadata, these observations are distinguished at the level of 'deployment'.

**Comment by meulenvd** [comment]
@joergklausen I am positive on the introduction of a variable as 'amount of precipitation from fog'. I am familiar with this phenomena in the coastal areas of Namibia and Maroc. To collect water from fog or ground touching clouds (coming from the sea) water collectors are developed catching the small water droplets very sucesfully. I think we need to define this variable (and also intensity) in such a way that it will not confuse with drizze. In pratice drizzle is reported by an observer (with intensity indication 'trace', PI < 0.1 mm/h) when fog gives a wetting effect on the surface but also on obstables and observed as very small droplets. Studies have shown that there is a direct relation between visibility (=MOR) and droplet size distributions of stable fog. So in practice a rough estimate can provide a 'potential amount of preciptable water from fog' using MOR measuring systems like scatterometers measuring the optical extinction of the air with aerosols including (small) water droplets (usually called present weather sensors or PWS). A serious issue is still the calibration of these measurements w/r precipitation intensity references for operational practices.

**Comment by SalomeKruger** [comment]
> https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22 notes:
> 
> * still under discussion, it's really about precipitation, possible variable name: "amount of precipitation from fog"
> * @SalomeKruger - are you ok if we don't do this and only add the method? We think that you can achieve what you need by using the code "amount of precipitation" in combination with the "fog collection" method.

@amilan17 - we can also consider adding it under the code "type of precipitation' to be combined with 'fog collection' method

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23](https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23) notes: 

*   not including in FT2022-2

**Comment by joergklausen** [comment]
Based on the discussion, TT-WIGOSMD confirms that 'precipitation from fog' can be expressed as 'amount of precipitation' and the (new) metod 'fog collection #388, which is expected to satisfy the requirement.

**Comment by amilan17** [comment]
no need to add, see comments above.
