### ISSUE TITLE
1-01-01 Add definitions to radiation variables

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#426]
### Initial request

Missing definitions of radiation variables need to be added in the code list.

### Amendment details

Include the following definitions:

|notation|path|name|description|
|-|-|-|-|
|	270	|	\Atmosphere\Radiation\Sunshine duration	|	Sunshine duration	| _missing_
|	273	|	\Atmosphere\Radiation\UV\UV-B radiation	|	UV-B radiation	| _missing_
|	356	|	\Atmosphere\Radiation\UV\UV Broadband	|	UV Broadband	| _missing_
|	357	|	\Atmosphere\Radiation\UV\UV Erythemally weighted	|	UV Erythemally weighted	| _missing_
|	358	|	\Atmosphere\Radiation\UV\UV Multiband	|	UV Multiband	| _missing_
|	359	|	\Atmosphere\Radiation\UV\UV Spectral	|	UV Spectral	| _missing_
|	565	|	\Atmosphere\Radiation\IR\Long-wave radiation (direction unspecified)	|	Long-wave radiation (direction unspecified)	| _*missing*_
|	571	|	\Atmosphere\Radiation\Solar\Diffuse solar radiation	|	Diffuse solar radiation	| _missing_
|	572	|	\Atmosphere\Radiation\Solar\Direct solar radiation	|	Direct solar radiation	| _missing_

Supersede following entries

current notation | current URL | new notation | name | description
-- | -- | -- | -- | --
566 | Long-wave radiation (downwelling) | tbd | Downward long-wave irradiance |Flux density of the downwelling long-wave radiation (heat emitted back to Earth from the atmosphere)
567 | Long-wave radiation (upwelling) |  tbd | Upward long-wave irradiance | Flux density of the upwelling long-wave radiation  (heat emitted from Earth back to the atmosphere)
573 | Global solar radiation (downwelling) | tbd | Downward short-wave irradiance | cf. https://github.com/wmo-im/wmds/issues/389
574 | Global solar radiation (upwelling) | tbd | Upward short-wave irradiance | cf. https://github.com/wmo-im/wmds/issues/389

### Requestor(s)

To be added later...

### Stakeholder(s)

To be added later...

### Publication(s)

To be added later...

### Expected impact of change

LOW

**Comment by fierz** [comment]
Sorry, that was a unvoluntary action. Should go back to submitted.

**Comment by joergklausen** [comment]
I suggest to replace instances of the term 'radiation' (notations 273, 565, 571, 572) with 'irradiance'.
Further, to add the term 'irradiance' where it is missing (notations 357, 358, 359).
Please comment.

**Comment by joergklausen** [comment]
Issue ready for branch creation.

**Comment by PeterBlattner** [comment]
@joergklausen  asked me to comment on #426. Here are my proposals/comments:

_273 UV-B radiation_
Proposed description: ultraviolet radiation covering the range from 280 nm to 315 nm.
Rational: ILV (https://cie.co.at/eilvterm/17-21-010 )  and IEV (https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=845-21-010 )

_356 UV Broadband_
Propose to change to "UV Broadband radiation" to be consistent with 273 and use the following description:
"spectrally integrated UV radiation"  
and add new term: "UV Radiation"
with the following description:
" optical radiation for which the wavelengths are shorter than those for visible radiation".
Rational: ILV (https://cie.co.at/eilvterm/17-21-008 ) and IEV https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=845-21-008 


_358 UV Erythemally weighted_
Propose to change into " erythemal radiation" to be consistent with 273 and use the following description: 
optical radiation effective in causing actinic erythema, Note 1 to entry: Ultraviolet radiation is the most effective erythemal radiation. Note 2 to entry: See also "erythema spectral weighting function".
Radional: ILV (https://cie.co.at/eilvterm/17-26-029 ) and IEV (https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=845-26-029 )

Add new entry: "erythema spectral weighting function " with the following description:
function representing the spectral dependence of the ability of [ultraviolet radiation](https://cie.co.at/eilvterm/17-21-008) to produce just perceptible [actinic erythema](https://cie.co.at/eilvterm/17-26-028) in human skin.
Rational: ILV (https://cie.co.at/eilvterm/17-26-065) and IEV (https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=845-26-065 )

_359 UV Spectral_
Not sure what is meant by this. The term "spectral-" is usually used in connection with a quantity (i.e. "spectral radiant flux"), see https://cie.co.at/eilvterm/17-21-027 or a distribution, see https://cie.co.at/eilvterm/17-21-028

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes:
* in the same boat as #389 and there is some mix up between the two
* @JREyre and @fstuerzl will determine whether to combine or the two issues

**Comment by AnnWebb** [comment]
Agree with Peter Blattner on using ILV  / IEV terms wherever possible for consistency outside as well as inside WMO.
I support his suggestions above for 273 and 358, and for having a new term for UV radiation, though his example begs the question of the short wavelength limit of visible radiation. UVA is usually specified 315-400 nm (see ILV) so perhaps specify less than 400 nm. The ILV lower limit of visible radiation is given as 'between 360 - 400 nm' and it would be better to avoid this uncertainty.

356 UV broadband radiation is indeed spectrally integrated UV radiation, but I would add a proviso that the wavelengths or waveband of integration should be specified, plus any weighting function (besides erythema, vitamin D and DNA weighting functions are used). The most common 'broadband UV' measurement is of erythemal radiation, and I think this would be the default understanding, but some instruments measure UVA or UVB or UVB+UVA with a (approximate) flat instrument response, rather than one representing erythema.

358 Multiband UV radiation - UV radiation measured across several discreet, narrow wavebands (e.g. 10nm)* within the UV, providing coarse spectral information

359 Spectral UV radiation - spectrally resolved measurements of UV radiation, at continuous and higher spectral resolution (e.g. 1 nm)* than multiband UV radiation.

* I'm aware that numbers may not be welcome but these are examples of current common measurement systems.

Erythemal, broadband, multiband and spectral UV radiation are most commonly measured as irradiance (i.e. on a flat horizontal surface). Direct beam spectral UV radiation is also used for determining atmospheric constituents e.g. ozone. See definition for direct solar radiation!

**Comment by JREyre** [comment]
@PeterBlattner @AnnWebb @fstuerzl @amilan17 
Thanks, Peter and Ann.
Franziska and I have been asked to combine this Issue (#426) with Issue #389 and consider the two together.  We will consider all you comments when we do this.
Just one general comment: this Issue is about variable names (name of geophysical variables) and not about methods of observations.  So we will try to ensure that what we do here is independent of specific technologies.  Would this lead you to modify any of your comments?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023-03-17-TT-WIGOSMD notes: 
work in progress (combining with #389)

**Comment by fstuerzl** [comment]
Proposed changes are included in #389, so this issue can be closed.
