### ISSUE TITLE
Table 1-01-05 Review Groundwater (amount per unit area)

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#433]
### Initial request

During the FT2022-2 review period, there were comments on this code that are summarized below. The team should review the validity of this code and consider deprecating or changing it. 
Noting, that there is now a new code in the Matrix table for groundwater. 
```
Notation: 165 
Name: Groundwater (amount per unit area)
Definition: Amount of water present beneath the ground surface per unit area.
```
Matrix table:
```
Notation: groundwater 
Name: Groundwater 
Definition: Subsurface water occupying the saturated zone. [International Glossary of Hydrology (WMO-No. 385). 2012.]
```
Comments: 
* Never seen 'groundwater' defined as a volume. 'Groundwater' is water present beneath the surface. Sometimes restricted to the saturated zone. https://water.usgs.gov/water-basics_glossary.html
* @jkorhonen said "My suggestion for the further FT is to remove this term totally, since I do not know if any member can have any measurements or values for amount per unit area this..."

### Amendment details

| notation | path | name | description |
| --- | --- | --- | --- |
| 165 | \Terrestrial\Groundwater\Groundwater (amount per unit area) | Groundwater (amount per unit area) | Amount of water present beneath the ground surface per unit area. Generally estimated by satellite gravity gradient observations. |

### Requestor(s)

claudia.ruz-vargas

### Stakeholder(s)

un-igrac

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 1-01-05

**Comment by JREyre** [comment]
@joergklausen @amilan17 @jkorhonen 
This variable should not be removed - it is in OSCAR/Requirements, and estimates of it are made from space using gravity gradient observations.
The remaining issues for me concern:
- the word "amount" - is it a mass or a volume?
- limitation to "the saturated zone"

**Comment by jbianchi81** [comment]
I guess that if it is measured by gravimetry then it should be a mass and should include the unsaturated zone

**Comment by jbianchi81** [comment]
Updated proposal based on comments. Added a reference to gravity gradient observations to give some context.

**Comment by jkorhonen** [comment]
@JREyre @jbianchi81 @amilan17 @joergklausen 

I come back to this groundwater (hydrology) variable discussion. 

I checked Groundwater in OSCAR/Requirements:
https://space.oscar.wmo.int/variables/view/ground_water
 
It says to be defined "Definitions and unit TBC by the terrestrial climate and hydrology community", and actually that requirement variable is not in use anymore related to any application area. 

@JREyre mentioned earlier that estimates are made from space using gravity gradient observations.

Our Groundwater specialist colleague from IGRAC commented to us related to space-based and the variable name: 
"The variable “groundwater amount” still does not make sense if it is space-based measured, since there is no device capable of measuring absolute amounts of groundwater on Earth. However, the variable could be replaced by “groundwater storage change”. The key word here is change, because this is something that can be estimated from the terrestrial water storage change and other datasets, which is what is derived from GRACE measurements. More info here: https://grace.jpl.nasa.gov/applications/groundwater/ and also here: https://www.g3p.eu/what-we-do "

In regards to above, we could still consider is the "Groundwater (amount per unit area)" 'the right variable' and do we want to keep it.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes:
not ready yet, @jbianchi81 update proposal summary with stakeholders and reviewers and work with them to make a final determination on whether to deprecate or update.

**Comment by amilan17** [comment]
meeting notes 31 January 2022: 
* John Eyre will contact the relevant people responsible for OSCAR SPACE to improve the requirement. 
* The hydrology community is working on improving the requirements in OSCAR.
* This issue can remain open until there is clarity from the requirements perspective.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.03.16-TT-WIGOSMD notes:
there was a meeting of hydrologists w/ John and Joerg (see notes above). OSCAR/Space has been updated; OSCAR/Requirements still need to be updated and this process may take a while.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.04.09%E2%80%90TT%E2%80%90WIGOSMD notes: 
John noted that we are still waiting for updates on the user requirements;

**Comment by JREyre** [comment]
@amilan17  @jkorhonen  
I also commented that I thought the name and definition of this variable were fine and that it was in use within the community.  It now appears in OSCAR/Space, and we await entries for requirements in OSCAR/Requirements.  If this is accepted (by Johanna and colleagues), it would seem logical to close this Issue.

**Comment by jkorhonen** [comment]
OK to close the issue with information provided by John.
