### ISSUE TITLE
Table 4-07, climate zone, As and Aw reversed

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wmds#479]
### Initial request

The name for the following climate zones appear to be reversed.

Equatorial - Savannah - dry winter
Equatorial - Savannah - dry summer

### Amendment details

Original:

|notation|name|description|
|--------|----|-----------|
equatorialSavannahDryWinter|**As**|Equatorial - Savannah - dry winter
equatorialSavannahDrySummer|**Aw**|Equatorial - Savannah - dry summer

Revised

|notation|name|description|
|--------|----|-----------|
equatorialSavannahDryWinter|**Aw**|Equatorial - Savannah - dry winter
equatorialSavannahDrySummer|**As**|Equatorial - Savannah - dry summer

### Comments

More information at: https://en.wikipedia.org/wiki/K%C3%B6ppen_climate_classification

### Requestor(s)

David Berry

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 1-02, Measurement unit,http://codes.wmo.int/wmdr/unit

### Expected impact of change

None

### References

https://en.wikipedia.org/wiki/K%C3%B6ppen_climate_classification

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.05.04-TT-WIGOSMD notes: 
Assigned to Shuli HANS and Anna will provide some guidance;

**Comment by hansl2022** [comment]
I have found some other information that can support this, as follows:
1)	Research paper
Kottek, M., J. Grieser, C. Beck, B. Rudolf, and F. Rubel, 2006: [World Map of the Köppen-Geiger climate classification updated](https://koeppen-geiger.vu-wien.ac.at/pdf/Paper_2006.pdf). Meteorol. Z., 15, 259-263. [DOI: 10.1127/0941-2948/2006/0130](https://dx.doi.org/10.1127/0941-2948/2006/0130).
2)	Website
https://koeppen-geiger.vu-wien.ac.at/koeppen.htm

**Comment by hansl2022** [comment]
The value of the drop-down menu of Climate zone on the Search page of OSCAR/Surface should make an adjustment. And may be OSCAR/Surface could evaluate whether there are other effects.

Thanks for Anna's help.

**Comment by joergklausen** [comment]
Branch updated.

**Comment by fstuerzl** [comment]
@hansl2022, for OSCAR this means the names "As" and "Aw" need to be switched in the database, so that the values in the drop-down menu consisting of name+description are correct. 

Also - unfortunately - the map service, used to automatically assign a climate zone based on the coordinates, needs to be updated. It uses a map according to https://doi.org/10.5194/hess-11-1633-2007, in which only Aw is shown. The map service translates this to "Equatorial savannah with dry summer", whereas it should be "Equatorial savannah with dry winter".

About 700 station records currently use either As or Aw in OSCAR. For these stations an evaluation, whether the classification is correct, should take place.

Anyway, the names As and Aw are clearly wrong and need to be switched - both in the code list and in OSCAR.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.01-TT-WIGOSMD notes: 
- impact is medium on OSCAR/Surface
- Anna create PR

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.15-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.15-TT-WIGOSMD) notes:

  
@joergklausen will review PR

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD) notes:

valid

**Comment by joergklausen** [comment]
@amilan17 Done. Please merge PR.
