### ISSUE TITLE
Table 5-02-01, add descriptions

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#499]
### Initial request

add descriptions to existing codes, this was originally a part of issue #336 

### Amendment details

notation | path | name | description
-- | -- | -- | --
190 | /Atmosphere/Visual range/Remote-sensing, active/ | Scatterometer | Visual range is calculated by measuring the return of light beam scattered by diffusion in air.
207 | /Atmosphere/Visual range/Remote-sensing, active/ | Transmissometer | Visual range is calculated by measuring the extinction coefficient of a beam of energy passing through a volume of air.
24 | /Atmosphere/Clouds/ | Human observation | Observation of clouds from the Earth's surface by a human observer (ref: https://cloudatlas.wmo.int/en/observation-of-clouds-from-the-earths-surface.html)

### Requestor(s)

TT-WIGOSMD

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry

### Expected impact of change

None

**Comment by meulenvd** [comment]
Both definitions to be harmonized because the technology and methods are comparable.
Visual range is only used for aeronautical practices: Runway Visual Range (RVR); Visual Range is for human beings, but subjective because a human beings vision qualities is undefined. Therefore, for meteorology the term visibility is used, which is equal to meteoprological optical range (MOR), which is a physical variable and uniquely related to the exctintion coefficient

190 | /Atmosphere/Visual range/Remote-sensing, active/ | Scatterometer | Visual range is calculated by measuring the return of light beam scattered by diffusion in air.

_proposal:_ Visual range is calculated by measuring the return of light beam scattered by diffusion in air. --> Visibility, determined from the relative amount of light scattered by a volume of air.

207 | /Atmosphere/Visual range/Remote-sensing, active/ | Transmissometer | Visual range is calculated by measuring the extinction coefficient of a beam of **energy** sent through a volume of air.

_proposal_: Visual range is calculated by measuring the extinction coefficient of a beam of energy sent through a volume of air. --> Visibility, determined from the relative amount of light passing a volume of air.

**Comment by joergklausen** [comment]
I support this, with maybe a slight addition: ... passing [through] a volume of air.

**Comment by meulenvd** [comment]
passing (through) is fine

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.01.18-TT-WIGOSMD notes:

@meulenvd -- I updated the proposal. (see issue summary at the top). If these changes are approved by you and the team within a week or two, we can include this proposal in FT2024-1.
