### ISSUE TITLE
update tables approved by EC69 to the latest version 

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#7]
The tables affiliated to this issue resulted from merging 
- the latest version on Google docs
- the reference tables used currently in OSCAR/Surface
- the EC69 approved code tables.

After approval by the TT they should serve as a baseline for the further work of the TT.

I will make a commit for each section i.e. in commit 1 we can discuss the changes of code table 1-05. In commit 2 we can discuss the changes to the tables 2-01 and 2-02 and so on.

**Comment by HoratN** [comment]
efucile created the branch https://github.com/wmo-im/wmds/tree/review_of_tables for this issue.

**Comment by efucile** [comment]
just to explain the process that we are going to follow with this. 
1. We are going to implement the changes in the branch  https://github.com/wmo-im/wmds/tree/review_of_tables
2. Comparing with master the changes will show the differences between EC69 and latest version. This changes have to be reviewed again and approved by some members of the team. In this context we need to register members with github so that they can make comments and interact with the system
3. When all the changes are ready and checked I will merge the branch with master and we will be able to release a first version on codes.wmo.int

**Comment by efucile** [comment]
Is this the same as getting the tables from OSCAR?
I am not sure. However we don't have a consolidated EC69 yet. @jenniferbest  is working on it.

**Comment by HoratN** [comment]
@efucile, @jenniferbest 
I would like to update the branch "review_of_EC69_tables" with the branch "review_of_tables". How can I do this? Starting from the baseline implemented in "review_of_tables" I will update the branch "review_of_EC69_tables" with the results from TT-WMD-7.
