### ISSUE TITLE
2-02 Programme/Network affiliation

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#75]
I just remarked that the amendments to table 2-02 proposed in this document [CodeTables_Revision_TT-WDM-6_Zurich_Nov2017_Doc.5.4v4_withedits.docx](https://github.com/wmo-im/wmds/files/2880651/CodeTables_Revision_TT-WDM-6_Zurich_Nov2017_Doc.5.4v4_withedits.docx)
 are not yet included in the development branch. @nuneslf Should that also be part of the new release?

**Comment by nuneslf** [comment]
Yes, I think they should be added, since this document was discussed at TT-WMD-6.

**Comment by LuisaIckes** [comment]
Added in branch [here](https://github.com/wmo-im/wmds/blob/issue75/), commit  6d0fe30. Could not merge it to the development branch because the first lines of this table is very different between master and the development branch and I do not know which version is correct.
@efucile: I do not know how to proceed with that?

**Comment by LuisaIckes** [comment]
Started again based on the development branch because the codetables were already too different between master and development  (and redoing everything Nina already did does not make sense). New branch for this issue is [issue75b](https://github.com/wmo-im/wmds/blob/issue75b/), commit 98e5cfd.
Merged into development in the end, close this issue.
