### ISSUE TITLE
Consistent naming throughout all tables

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#77]
I realized that the naming for the columns is not consistent throughout all tables. I guess it would be good if we agree on a consistent naming for the columns, or is there a reason that it is sometimes name and sometimes name_e etc.?

**Comment by nuneslf** [comment]
I strongly support that, preferably with simple/clear names.
On the other hand, why not to align with the Code Registry and use: Name | Notation | Description ?

**Comment by LuisaIckes** [comment]
Sounds good to me, does the _e has a certain meaning/is needed?

**Comment by ebuyukbas** [comment]
I agree on having a consistent naming for the columns.

**Comment by HoratN** [comment]
The _e originates from the multilingual version:

WMO306CD_efrs | QualityFlagSysURL_efrs | Path_e | Name_e | Definition_e | Path_f | Name_f | Definition_f | Path_s | Name_s | Definition_s | Path_r | Name_r | Definition_r

I think that we should keep this _e at least here in GitHub. For the approval process, 'name' without '_e' is fine for me. 

I am in favor of switching from 'Definition' to 'Description' in order to align better with the codes registry. But the term 'Notation' is not that clear for me. Thus I would prefer to keep the heading WMO306CD.

**Comment by LuisaIckes** [comment]
Ok, now I understand the _e. I will delete/rename it in the last step before the release because we need the final versions in github before they go into the code registry. I can checkout another branch just before I do this change as a backup.

I am going to change 'Definition' to 'Description' as suggested by @HoratN.
We will use 'Notation' instead of WMO306CD (because this is rather cryptic).

**Comment by LuisaIckes** [comment]
Copy with old namings before I started [here](https://github.com/wmo-im/wmds/tree/Development-backup-old-namings), branch with changed names [here](https://github.com/wmo-im/wmds/tree/issue77).
