### ISSUE TITLE
column 'status' in table 1-04, 10-01

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#81]
Do we need the column ‘status’ in table 1-04 and 10-01?
For me this seems to be a relic from the task team internal discussion.

**Comment by nuneslf** [comment]
I think that for this release we shouldn't have such a column, because it is not needed - we have now been using Github for registering and tracking all the issues/comments during approval of changes.
The TT-WMD might wish to reopen this issue at a later stage, but for now I suggest to remove that column in the mentioned tables and close the issue.

**Comment by LuisaIckes** [comment]
Added it through branch [issue81](https://github.com/wmo-im/wmds/tree/issue81) (Table 1-04, Table 10-01 by accident directly in the Development branch).
