### ISSUE TITLE
5-05 "Type of reference surface" new table; Deadline 5th April 2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#88]
On OSCAR we have the following entries for this table:
name,notation
local ground,localGround
sea surface,seaSurface
ship deck,shipDeck
(other),other

Definitions for these entries need to be provided and perhaps also some new entries need to be amended.

Has the TT once discussed this table and might there exist an other version? I already checked GoogleDocs and found nothing there.

**Comment by joergklausen** [comment]
Definitions proposed as follows:

local ground,localGround: The natural interface between the atmosphere and the terrestrial sphere, not artificially elevated with respect to the surrounding area on a scale of 50 meters.
sea surface,seaSurface: The natural interface between the atmosphere and the ocean
ship deck,shipDeck: A permanent covering over a compartment or the body of a ship. also the horizontal structure that forms the "roof" of the hull, elevated with respect to the surrounding sea surface
roof,roof: the top of a building, elevated with respect to the surrounding local ground

(other),other: other reference service
Please also include “unknown”, “inapplicable”

**Comment by nuneslf** [comment]
I suggest to set the deadline for this discussion to Friday 5 April 2019.

My comments and other suggestions are below:
(New proposed text in upper-case, text to delete in brackets, question/comment in " ")

local ground,localGround: The natural interface between the atmosphere and the terrestrial GLOBE (sphere), not artificially elevated with respect to the NEARBY surrounding area (on a scale of 50 meters).

ARTIFICIAL ground,ARTIFICIALGround: The ARTIFICIAL interface between the atmosphere and the terrestrial GLOBE (sphere), not artificially elevated with respect to the NEARBY surrounding area (on a scale of 50 meters).

sea surface,seaSurface: The natural interface between the atmosphere and the ocean

ship deck,shipDeck: A permanent covering over a compartment or the body of a ship. also the horizontal structure that forms the "roof" of the hull, elevated with respect to the surrounding sea surface

roof,roof: A PLATFORM ON the top of a building, elevated with respect to the surrounding local ground

(other),other: other reference service  "<- Do we need this entry?"

unknown

inapplicable

**Comment by LuisaIckes** [comment]
Added the deadline in the title, maybe we can do that always like this for new issues (with a approx. 30 days deadline) in future if it is not a technical change/typo thing (lavendel label)...

**Comment by joergklausen** [comment]
I cannot support 'artificial ground', also a ship deck and a roof top are artificial grounds. 
The current entries do not describe the 'make' of the reference surface in detail, and this is for good reason. If we wanted to do this (and I could see reasons for doing this), we should develop an entirely new reference table. Local ground can be grass or shrubs or concrete or sand or ... The fundamental reason for this table is a different one: it is more to express the fact that a sensor may be elevated above the 'average' elevation of the nearby surroundings if it is mounted on a ship or a roof.

roof: I am not sure that adding 'a platform on [the top of ...] is needed.

(other), other, other reference surface (not service!)

unknown and inapplicable make sense.

**Comment by HoratN** [comment]
TT-WMD 17.4.2019
- replace roof by building roof
- local ground: rename into natural ground
- add artificial ground
- other: replace by inapplicable
- add unknown

definitions:
roof,roof: the top of a building, elevated with respect to the surrounding local ground

**Comment by LuisaIckes** [comment]
Luis and me suggest to remove the "artificially" in front of elevated in the definition of artificial and natural ground. Otherwise "The artificial interface between the atmosphere and the terrestrial globe (sphere), not **artificially** elevated with respect to the nearby surrounding area (on a scale of 50 meters)."  sounds a bit strange. It is very unlikely to have a natural elevation that does fit in the definition....

**Comment by joergklausen** [comment]
@LuisaIckes Where do I find the current version of this table, please?

**Comment by LuisaIckes** [comment]
Here is the new suggested version:
https://github.com/wmo-im/wmds/blob/issue88/tables_en/5-05.csv

**Comment by joergklausen** [comment]
Can we agree on the following editorial improvements? It occurs to me that the current definitions define the interface, whic is actually not correct.

notation 	name 	description
naturalGround 	natural ground 	A natural surface at the interface between the atmosphere and the terrestrial globe (sphere), not artificially elevated with respect to the nearby surrounding area (on a scale of 50 meters)
artificialGround 	artificial ground 	An artificial surface at the interface between the atmosphere and the terrestrial globe (sphere), not artificially elevated with respect to the nearby surrounding area (on a scale of 50 meters)
seaSurface 	sea surface 	The natural surface of the sea at the interface between the atmosphere and the ocean

**Comment by nuneslf** [comment]
Building on Jörg's latest version, I suggest the changes below (deletions in brackets and additions in upper-case):
notation name description
naturalGround natural ground A natural surface at the interface between the atmosphere and the terrestrial globe [delete: (sphere)], [delete: artificially] not elevated with respect to the nearby surrounding area (on a scale of 50 meters)
artificialGround artificial ground An artificial surface at the interface between the atmosphere and the terrestrial globe [delete: (sphere)], [delete: artificially] not elevated with respect to the nearby surrounding area (on a scale of 50 meters)
seaSurface sea surface The natural surface of the sea at the interface between the atmosphere and the ocean
[delete: ship] deck	A permanent covering over a compartment or the body of a FIXED OR MOBILE PLATFORM (ship). Also the horizontal structure that forms the roof of the hull, elevated with respect to the surrounding sea surface
buildingRoof	building roof	The top OR OTHER ELEVATED PART of a building,  [delete: elevated] with respect to the surrounding local ground

**Comment by joergklausen** [comment]
@nuneslf I am almost happy with these further improvements, except the following, where I would suggest 

buildingRoof building roof The top OR OTHER PART of a building, ELEVATED with respect to the surrounding local ground.

To me, this would highlight that this is higher than the surrounding area, and the wording would parallel the wording in the other definitions.

**Comment by LuisaIckes** [comment]
I am a bit confused by "building roof = OTHER PART of a building, ELEVATED with respect to the surrounding local ground" - a balcony is also a part of a building that is elevated but that is not a roof?

**Comment by nuneslf** [comment]
I agree with @joergklausen but I also see @LuisaIckes's point, so I suggest an alternative name and definition:
building building The roof or other of a building, elevated with respect to the surrounding local ground.

**Comment by LuisaIckes** [comment]
@nuneslf @joergklausen :
building building The roof or other part of a building, elevated with respect to the surrounding local ground.
?

**Comment by nuneslf** [comment]
Yes, that's what I intended to write, sorry, getting tired here...

**Comment by joergklausen** [comment]
This is getting complicated ... if an instrument is indeed mounted on a balcony, then the local ground is probably rather the ground on which the building stands, and not the building. The original intention of this is really better captured with
roof, roof, The roof of a building, elevated with respect to the surrounding local ground.

If balconies and other mountings need to be considered, then the reason is probably also the obstruction effected by this, but this is not the 'vertical distance from reference surface'. It may be a different matter with a terrasse (which is open to the sky), so instead of the above, we might also consider

roofTerrasse, roof or terrasse, The roof or terrasse of a building, elevated with respect to the surrounding local ground.

**Comment by nuneslf** [comment]
That makes me re-think about the whole concept of WMDS element 5-05, which is to describe the vertical distance of the sensor from a (specified) reference level - please see picture attached. So, if the reference surface is a terrace (elevated by distance "b1") and the sensor is elevated by distance "a" above the reference surface, what should be the elevation reported in elements 3-07 and 5-12 (Geospatial location): "c"+"b1"?
Regarding other types of installation where the sensor is directly exposed to the local ground, the vertical distance should be just "b2"?
![IMG_20190617_100900](https://user-images.githubusercontent.com/42995432/59588861-da40c100-90e8-11e9-8a51-2735db14837f.jpg)

**Comment by LuisaIckes** [comment]
I am not sure if adding an entry roofTerasse in addition to roof with the exactly same description helps/is very clear, in that case building (meaning any part of a building) is maybe less confusing?

**Comment by joergklausen** [comment]
@LuisaIckes roofTerrasse was meant to be an alternative to roof.
@nuneslf It is up to the user to specify the reference surface. In your image, if the building has no effect on the observations, then the reference surface should be the local ground, not the roof, but if the roof is large enough to influence the observation (as an obstruction to the flow, or because of albedo, etc), then the reference surface should be the roof (or terrasse). The elevations to be reported for the sensors are always absolute (geospatial position!), precisely to avoid this type of confusion.

**Comment by nuneslf** [comment]
@joergklausen I agree with your proposed entry "roofTerrasse, roof or terrasse, The roof or terrasse of a building, elevated with respect to the surrounding local ground".
I don't agree with the statement that "if the building has no effect on the observations, then the reference surface should be the local ground", because a building has always some influence on the measurements; So, I would not use that as a recommendation.

**Comment by LuisaIckes** [comment]
Changes can be found in [issue88](https://github.com/wmo-im/wmds/tree/issue88).
