### ISSUE TITLE
1-02, 1-04 typos Release 1.0RC1 english only; Deadline 1.4.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#92]
table 1-02 units
- μg-m-3_25C, micrograms per cubic metre at 25 degrees,
should be 
μg_m-3_25C, micrograms per cubic metre at 25 degrees,

**Comment by HoratN** [comment]
table 1-04 Geometry
- The first column called 'ID' should be removed. We use the notation as the unique identifier instead.

**Comment by LuisaIckes** [comment]
Not sure if it is good to combine several typos or typo issues in one issue. I think it would be better to have a separate typo issue for each table, also that makes the list rather long... But since it is only a typo issue it does not stay here 4 weeks and can be closed rather soon after the change has been addressed.

**Comment by nuneslf** [comment]
I support Luisa's comment. And let's give each typo related issue, one week for comments and closing.

**Comment by HoratN** [comment]
Thanks for your feedback. I will open new issues for the typos still coming.

**Comment by HoratN** [comment]
implemented changes on branch [issue92](https://github.com/wmo-im/wmds/tree/issue92), can be merged onto development
